# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addcarone.ui'
#
# Created: Sun Sep 17 19:33:25 2017
#      by: PyQt5 UI code generator 5.3.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_addcarone(object):
    def setupUi(self, addcarone):
        addcarone.setObjectName("addcarone")
        addcarone.resize(808, 460)
        addcarone.setStyleSheet("QLabel{\n"
"font-size:15px;\n"
"}\n"
"QLineEdit{\n"
"font-size:15px; \n"
"}\n"
"QPushButton{\n"
"font-size:15px;\n"
"}\n"
"QDateEdit{\n"
"font-size:15px;\n"
"}\n"
"QComboBox{\n"
"font-size:15px;\n"
"}")
        self.label = QtWidgets.QLabel(addcarone)
        self.label.setGeometry(QtCore.QRect(320, 30, 191, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(addcarone)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 141, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(addcarone)
        self.label_3.setGeometry(QtCore.QRect(30, 120, 101, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(addcarone)
        self.label_4.setGeometry(QtCore.QRect(30, 160, 131, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(addcarone)
        self.label_5.setGeometry(QtCore.QRect(30, 200, 121, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(addcarone)
        self.label_6.setGeometry(QtCore.QRect(30, 250, 46, 13))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(addcarone)
        self.label_7.setGeometry(QtCore.QRect(30, 230, 151, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(addcarone)
        self.label_8.setGeometry(QtCore.QRect(30, 280, 91, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(addcarone)
        self.label_9.setGeometry(QtCore.QRect(30, 310, 101, 31))
        self.label_9.setObjectName("label_9")
        self.licensenumber = QtWidgets.QLineEdit(addcarone)
        self.licensenumber.setGeometry(QtCore.QRect(210, 80, 181, 31))
        self.licensenumber.setObjectName("licensenumber")
        self.initial_mileage = QtWidgets.QLineEdit(addcarone)
        self.initial_mileage.setGeometry(QtCore.QRect(210, 240, 181, 31))
        self.initial_mileage.setObjectName("initial_mileage")
        self.carmake = QtWidgets.QLineEdit(addcarone)
        self.carmake.setGeometry(QtCore.QRect(210, 280, 181, 31))
        self.carmake.setObjectName("carmake")
        self.cartype = QtWidgets.QLineEdit(addcarone)
        self.cartype.setGeometry(QtCore.QRect(210, 320, 181, 31))
        self.cartype.setObjectName("cartype")
        self.carmodel = QtWidgets.QLineEdit(addcarone)
        self.carmodel.setGeometry(QtCore.QRect(210, 120, 181, 31))
        self.carmodel.setObjectName("carmodel")
        self.manudate = QtWidgets.QDateEdit(addcarone)
        self.manudate.setGeometry(QtCore.QRect(210, 160, 181, 31))
        self.manudate.setObjectName("manudate")
        self.fuel_type = QtWidgets.QComboBox(addcarone)
        self.fuel_type.setGeometry(QtCore.QRect(210, 200, 181, 31))
        self.fuel_type.setObjectName("fuel_type")
        self.fuel_type.addItem("")
        self.fuel_type.addItem("")
        self.label_10 = QtWidgets.QLabel(addcarone)
        self.label_10.setGeometry(QtCore.QRect(420, 290, 141, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(addcarone)
        self.label_11.setGeometry(QtCore.QRect(420, 330, 131, 21))
        self.label_11.setObjectName("label_11")
        self.addcar = QtWidgets.QPushButton(addcarone)
        self.addcar.setGeometry(QtCore.QRect(320, 410, 181, 31))
        self.addcar.setObjectName("addcar")
        self.InsuranceCompany = QtWidgets.QLabel(addcarone)
        self.InsuranceCompany.setGeometry(QtCore.QRect(420, 120, 151, 21))
        self.InsuranceCompany.setObjectName("InsuranceCompany")
        self.chasisnumber = QtWidgets.QLineEdit(addcarone)
        self.chasisnumber.setGeometry(QtCore.QRect(210, 360, 181, 31))
        self.chasisnumber.setObjectName("chasisnumber")
        self.expirydate = QtWidgets.QDateEdit(addcarone)
        self.expirydate.setGeometry(QtCore.QRect(600, 200, 181, 31))
        self.expirydate.setObjectName("expirydate")
        self.subscriptiondate = QtWidgets.QDateEdit(addcarone)
        self.subscriptiondate.setGeometry(QtCore.QRect(600, 160, 181, 31))
        self.subscriptiondate.setObjectName("subscriptiondate")
        self.carcolor = QtWidgets.QLineEdit(addcarone)
        self.carcolor.setGeometry(QtCore.QRect(600, 80, 181, 31))
        self.carcolor.setObjectName("carcolor")
        self.label_13 = QtWidgets.QLabel(addcarone)
        self.label_13.setGeometry(QtCore.QRect(420, 240, 121, 21))
        self.label_13.setObjectName("label_13")
        self.lineEdit_7 = QtWidgets.QLineEdit(addcarone)
        self.lineEdit_7.setGeometry(QtCore.QRect(600, 120, 181, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_14 = QtWidgets.QLabel(addcarone)
        self.label_14.setGeometry(QtCore.QRect(420, 80, 151, 20))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(addcarone)
        self.label_15.setGeometry(QtCore.QRect(420, 360, 121, 21))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(addcarone)
        self.label_16.setGeometry(QtCore.QRect(410, 160, 181, 31))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(addcarone)
        self.label_17.setGeometry(QtCore.QRect(30, 350, 161, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(addcarone)
        self.label_18.setGeometry(QtCore.QRect(420, 200, 151, 31))
        self.label_18.setObjectName("label_18")
        self.lineEdit = QtWidgets.QLineEdit(addcarone)
        self.lineEdit.setGeometry(QtCore.QRect(600, 240, 181, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(addcarone)
        self.lineEdit_2.setGeometry(QtCore.QRect(600, 320, 181, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(addcarone)
        self.lineEdit_3.setGeometry(QtCore.QRect(600, 280, 181, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(addcarone)
        self.lineEdit_4.setGeometry(QtCore.QRect(600, 360, 181, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")

        self.retranslateUi(addcarone)
        QtCore.QMetaObject.connectSlotsByName(addcarone)
        addcarone.setTabOrder(self.licensenumber, self.carmodel)
        addcarone.setTabOrder(self.carmodel, self.manudate)
        addcarone.setTabOrder(self.manudate, self.fuel_type)
        addcarone.setTabOrder(self.fuel_type, self.initial_mileage)
        addcarone.setTabOrder(self.initial_mileage, self.carmake)
        addcarone.setTabOrder(self.carmake, self.cartype)
        addcarone.setTabOrder(self.cartype, self.chasisnumber)
        addcarone.setTabOrder(self.chasisnumber, self.carcolor)
        addcarone.setTabOrder(self.carcolor, self.lineEdit_7)
        addcarone.setTabOrder(self.lineEdit_7, self.subscriptiondate)
        addcarone.setTabOrder(self.subscriptiondate, self.expirydate)
        addcarone.setTabOrder(self.expirydate, self.addcar)

    def retranslateUi(self, addcarone):
        _translate = QtCore.QCoreApplication.translate
        addcarone.setWindowTitle(_translate("addcarone", "Add Car"))
        self.label.setText(_translate("addcarone", "ADD CAR DETAILS"))
        self.label_2.setText(_translate("addcarone", "License plate number"))
        self.label_3.setText(_translate("addcarone", "Car Model"))
        self.label_4.setText(_translate("addcarone", "Manufacture Date"))
        self.label_5.setText(_translate("addcarone", "Fuel Type"))
        self.label_7.setText(_translate("addcarone", "Mileage"))
        self.label_8.setText(_translate("addcarone", "Make"))
        self.label_9.setText(_translate("addcarone", "Type"))
        self.fuel_type.setItemText(0, _translate("addcarone", "Petrol"))
        self.fuel_type.setItemText(1, _translate("addcarone", "Deisel"))
        self.label_10.setText(_translate("addcarone", "Right Side Photo"))
        self.label_11.setText(_translate("addcarone", "Left Side Photo"))
        self.addcar.setText(_translate("addcarone", "Add Car"))
        self.InsuranceCompany.setText(_translate("addcarone", "Insurance Company"))
        self.label_13.setText(_translate("addcarone", "Front Photo"))
        self.label_14.setText(_translate("addcarone", "Color"))
        self.label_15.setText(_translate("addcarone", "Behind Photo"))
        self.label_16.setText(_translate("addcarone", "3rd Party Subscpriton date"))
        self.label_17.setText(_translate("addcarone", "Chasis Number"))
        self.label_18.setText(_translate("addcarone", "3rd party expiry date"))

