# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fleetsystem.ui'
#
# Created: Tue Sep 19 13:37:29 2017
#      by: PyQt5 UI code generator 5.3.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_fleetx(object):
    def setupUi(self, fleetx):
        fleetx.setObjectName("fleetx")
        fleetx.resize(800, 600)
        fleetx.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/fleets.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        fleetx.setWindowIcon(icon)
        fleetx.setAutoFillBackground(True)
        fleetx.setStyleSheet("QMenuBar::item::selected{\n"
"color:#ffffff; background-color:#00bfff;\n"
"}\n"
"QMenu::item::selected{\n"
"color:#ffffff; background-color:#00bfff;\n"
"}\n"
"QTableWidget{\n"
"border:0px;\n"
"}\n"
"QTabWidget{\n"
"background-color:#ffffff; \n"
"}\n"
"QLabel{\n"
"font-size:15px;\n"
"}\n"
"QLineEdit{\n"
"font-size:15px; \n"
"}\n"
"QPushButton{\n"
"font-size:15px;\n"
"}\n"
"QDateEdit{\n"
"font-size:15px;\n"
"}\n"
"QComboBox{\n"
"font-size:15px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(fleetx)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainstack = QtWidgets.QStackedWidget(self.centralwidget)
        self.mainstack.setObjectName("mainstack")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(260, 200, 121, 16))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(260, 150, 81, 31))
        self.label_2.setObjectName("label_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_4.setGeometry(QtCore.QRect(410, 280, 171, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(360, 120, 101, 16))
        self.label.setObjectName("label")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_3.setGeometry(QtCore.QRect(410, 240, 171, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setGeometry(QtCore.QRect(370, 330, 131, 31))
        self.pushButton.setObjectName("pushButton")
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setGeometry(QtCore.QRect(260, 240, 71, 16))
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(260, 280, 121, 21))
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(self.page)
        self.lineEdit.setGeometry(QtCore.QRect(410, 160, 171, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_2.setGeometry(QtCore.QRect(410, 200, 171, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.mainstack.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_10 = QtWidgets.QLabel(self.page_2)
        self.label_10.setGeometry(QtCore.QRect(260, 290, 151, 31))
        self.label_10.setObjectName("label_10")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setGeometry(QtCore.QRect(400, 10, 131, 31))
        self.label_4.setObjectName("label_4")
        self.permitnumber = QtWidgets.QLineEdit(self.page_2)
        self.permitnumber.setGeometry(QtCore.QRect(380, 340, 201, 31))
        self.permitnumber.setObjectName("permitnumber")
        self.emaildriver = QtWidgets.QLineEdit(self.page_2)
        self.emaildriver.setGeometry(QtCore.QRect(390, 170, 201, 31))
        self.emaildriver.setObjectName("emaildriver")
        self.female = QtWidgets.QCheckBox(self.page_2)
        self.female.setGeometry(QtCore.QRect(510, 290, 70, 17))
        self.female.setObjectName("female")
        self.lnamedrive = QtWidgets.QLineEdit(self.page_2)
        self.lnamedrive.setGeometry(QtCore.QRect(390, 90, 201, 31))
        self.lnamedrive.setObjectName("lnamedrive")
        self.label_8 = QtWidgets.QLabel(self.page_2)
        self.label_8.setGeometry(QtCore.QRect(260, 250, 131, 31))
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setGeometry(QtCore.QRect(260, 340, 151, 31))
        self.label_7.setObjectName("label_7")
        self.drivephoto = QtWidgets.QLineEdit(self.page_2)
        self.drivephoto.setGeometry(QtCore.QRect(380, 420, 201, 31))
        self.drivephoto.setObjectName("drivephoto")
        self.label_9 = QtWidgets.QLabel(self.page_2)
        self.label_9.setGeometry(QtCore.QRect(260, 380, 131, 31))
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.page_2)
        self.label_11.setGeometry(QtCore.QRect(260, 50, 101, 21))
        self.label_11.setObjectName("label_11")
        self.birthdate = QtWidgets.QDateEdit(self.page_2)
        self.birthdate.setGeometry(QtCore.QRect(390, 251, 181, 31))
        self.birthdate.setObjectName("birthdate")
        self.fnamedrive = QtWidgets.QLineEdit(self.page_2)
        self.fnamedrive.setGeometry(QtCore.QRect(390, 50, 201, 31))
        self.fnamedrive.setObjectName("fnamedrive")
        self.addressdrive = QtWidgets.QLineEdit(self.page_2)
        self.addressdrive.setGeometry(QtCore.QRect(390, 210, 201, 31))
        self.addressdrive.setObjectName("addressdrive")
        self.label_12 = QtWidgets.QLabel(self.page_2)
        self.label_12.setGeometry(QtCore.QRect(260, 420, 141, 31))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.page_2)
        self.label_13.setGeometry(QtCore.QRect(260, 90, 131, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.page_2)
        self.label_14.setGeometry(QtCore.QRect(260, 210, 121, 31))
        self.label_14.setObjectName("label_14")
        self.phonedrive = QtWidgets.QLineEdit(self.page_2)
        self.phonedrive.setGeometry(QtCore.QRect(390, 130, 201, 31))
        self.phonedrive.setObjectName("phonedrive")
        self.label_15 = QtWidgets.QLabel(self.page_2)
        self.label_15.setGeometry(QtCore.QRect(260, 170, 101, 31))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.page_2)
        self.label_16.setGeometry(QtCore.QRect(260, 130, 121, 21))
        self.label_16.setObjectName("label_16")
        self.permitclass = QtWidgets.QLineEdit(self.page_2)
        self.permitclass.setGeometry(QtCore.QRect(380, 380, 201, 31))
        self.permitclass.setObjectName("permitclass")
        self.male = QtWidgets.QCheckBox(self.page_2)
        self.male.setGeometry(QtCore.QRect(410, 290, 70, 17))
        self.male.setObjectName("male")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 490, 131, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.mainstack.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_17 = QtWidgets.QLabel(self.page_3)
        self.label_17.setGeometry(QtCore.QRect(170, 140, 141, 31))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.page_3)
        self.label_18.setGeometry(QtCore.QRect(170, 180, 131, 31))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.page_3)
        self.label_19.setGeometry(QtCore.QRect(170, 60, 171, 21))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.page_3)
        self.label_20.setGeometry(QtCore.QRect(170, 250, 141, 31))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.page_3)
        self.label_21.setGeometry(QtCore.QRect(335, 30, 131, 20))
        self.label_21.setObjectName("label_21")
        self.dateservice = QtWidgets.QDateEdit(self.page_3)
        self.dateservice.setGeometry(QtCore.QRect(440, 260, 221, 31))
        self.dateservice.setObjectName("dateservice")
        self.label_22 = QtWidgets.QLabel(self.page_3)
        self.label_22.setGeometry(QtCore.QRect(170, 320, 141, 31))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.page_3)
        self.label_23.setGeometry(QtCore.QRect(170, 100, 131, 21))
        self.label_23.setObjectName("label_23")
        self.servicedescription = QtWidgets.QTextEdit(self.page_3)
        self.servicedescription.setGeometry(QtCore.QRect(440, 300, 221, 101))
        self.servicedescription.setObjectName("servicedescription")
        self.label_24 = QtWidgets.QLabel(self.page_3)
        self.label_24.setGeometry(QtCore.QRect(180, 420, 131, 21))
        self.label_24.setObjectName("label_24")
        self.submitservice = QtWidgets.QPushButton(self.page_3)
        self.submitservice.setGeometry(QtCore.QRect(300, 470, 131, 31))
        self.submitservice.setObjectName("submitservice")
        self.numcarserv = QtWidgets.QLineEdit(self.page_3)
        self.numcarserv.setGeometry(QtCore.QRect(440, 60, 221, 31))
        self.numcarserv.setObjectName("numcarserv")
        self.serviceinvoice = QtWidgets.QLineEdit(self.page_3)
        self.serviceinvoice.setGeometry(QtCore.QRect(440, 410, 181, 31))
        self.serviceinvoice.setObjectName("serviceinvoice")
        self.partsservice = QtWidgets.QTextEdit(self.page_3)
        self.partsservice.setGeometry(QtCore.QRect(440, 180, 221, 71))
        self.partsservice.setObjectName("partsservice")
        self.drivernumserv = QtWidgets.QLineEdit(self.page_3)
        self.drivernumserv.setGeometry(QtCore.QRect(440, 100, 221, 31))
        self.drivernumserv.setObjectName("drivernumserv")
        self.servicetype = QtWidgets.QLineEdit(self.page_3)
        self.servicetype.setGeometry(QtCore.QRect(440, 140, 221, 31))
        self.servicetype.setObjectName("servicetype")
        self.mainstack.addWidget(self.page_3)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_57 = QtWidgets.QLabel(self.page_9)
        self.label_57.setObjectName("label_57")
        self.verticalLayout_2.addWidget(self.label_57)
        self.carreport = QtWidgets.QTableWidget(self.page_9)
        self.carreport.setAutoFillBackground(True)
        self.carreport.setObjectName("carreport")
        self.carreport.setColumnCount(6)
        self.carreport.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.carreport.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.carreport.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.carreport.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.carreport.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.carreport.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.carreport.setHorizontalHeaderItem(5, item)
        self.verticalLayout_2.addWidget(self.carreport)
        self.mainstack.addWidget(self.page_9)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.page_8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.drivelist = QtWidgets.QTableWidget(self.page_8)
        self.drivelist.setObjectName("drivelist")
        self.drivelist.setColumnCount(5)
        self.drivelist.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.drivelist.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.drivelist.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.drivelist.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.drivelist.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.drivelist.setHorizontalHeaderItem(4, item)
        self.horizontalLayout.addWidget(self.drivelist)
        self.mainstack.addWidget(self.page_8)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.frame = QtWidgets.QFrame(self.page_4)
        self.frame.setGeometry(QtCore.QRect(0, 10, 775, 451))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_7.setGeometry(QtCore.QRect(580, 100, 181, 31))
        self.lineEdit_7.setAutoFillBackground(False)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_25 = QtWidgets.QLabel(self.frame)
        self.label_25.setGeometry(QtCore.QRect(10, 290, 101, 31))
        self.label_25.setObjectName("label_25")
        self.initial_mileage = QtWidgets.QLineEdit(self.frame)
        self.initial_mileage.setGeometry(QtCore.QRect(190, 220, 181, 31))
        self.initial_mileage.setAutoFillBackground(False)
        self.initial_mileage.setObjectName("initial_mileage")
        self.label_26 = QtWidgets.QLabel(self.frame)
        self.label_26.setGeometry(QtCore.QRect(10, 230, 46, 13))
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_5.setGeometry(QtCore.QRect(580, 340, 181, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.manudate = QtWidgets.QDateEdit(self.frame)
        self.manudate.setGeometry(QtCore.QRect(190, 140, 181, 31))
        self.manudate.setAutoFillBackground(True)
        self.manudate.setObjectName("manudate")
        self.label_27 = QtWidgets.QLabel(self.frame)
        self.label_27.setGeometry(QtCore.QRect(10, 60, 141, 31))
        self.label_27.setObjectName("label_27")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_6.setGeometry(QtCore.QRect(580, 260, 181, 31))
        self.lineEdit_6.setAutoFillBackground(False)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.fuel_type = QtWidgets.QComboBox(self.frame)
        self.fuel_type.setGeometry(QtCore.QRect(190, 180, 181, 31))
        self.fuel_type.setAutoFillBackground(True)
        self.fuel_type.setObjectName("fuel_type")
        self.fuel_type.addItem("")
        self.fuel_type.addItem("")
        self.label_28 = QtWidgets.QLabel(self.frame)
        self.label_28.setGeometry(QtCore.QRect(400, 60, 151, 20))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.frame)
        self.label_29.setGeometry(QtCore.QRect(10, 180, 121, 21))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame)
        self.label_30.setGeometry(QtCore.QRect(400, 310, 131, 21))
        self.label_30.setObjectName("label_30")
        self.expirydate = QtWidgets.QDateEdit(self.frame)
        self.expirydate.setGeometry(QtCore.QRect(580, 180, 181, 31))
        self.expirydate.setObjectName("expirydate")
        self.subscriptiondate = QtWidgets.QDateEdit(self.frame)
        self.subscriptiondate.setGeometry(QtCore.QRect(580, 140, 181, 31))
        self.subscriptiondate.setAutoFillBackground(True)
        self.subscriptiondate.setObjectName("subscriptiondate")
        self.label_31 = QtWidgets.QLabel(self.frame)
        self.label_31.setGeometry(QtCore.QRect(300, 10, 191, 31))
        self.label_31.setObjectName("label_31")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_8.setGeometry(QtCore.QRect(580, 220, 181, 31))
        self.lineEdit_8.setAutoFillBackground(False)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_32 = QtWidgets.QLabel(self.frame)
        self.label_32.setGeometry(QtCore.QRect(10, 140, 131, 31))
        self.label_32.setObjectName("label_32")
        self.InsuranceCompany = QtWidgets.QLabel(self.frame)
        self.InsuranceCompany.setGeometry(QtCore.QRect(400, 100, 151, 21))
        self.InsuranceCompany.setObjectName("InsuranceCompany")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_9.setGeometry(QtCore.QRect(580, 300, 181, 31))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.addcar = QtWidgets.QPushButton(self.frame)
        self.addcar.setGeometry(QtCore.QRect(300, 390, 181, 31))
        self.addcar.setAutoFillBackground(True)
        self.addcar.setObjectName("addcar")
        self.label_33 = QtWidgets.QLabel(self.frame)
        self.label_33.setGeometry(QtCore.QRect(400, 270, 141, 21))
        self.label_33.setObjectName("label_33")
        self.carcolor = QtWidgets.QLineEdit(self.frame)
        self.carcolor.setGeometry(QtCore.QRect(580, 60, 181, 31))
        self.carcolor.setAutoFillBackground(False)
        self.carcolor.setObjectName("carcolor")
        self.label_34 = QtWidgets.QLabel(self.frame)
        self.label_34.setGeometry(QtCore.QRect(400, 220, 121, 21))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.frame)
        self.label_35.setGeometry(QtCore.QRect(400, 340, 121, 21))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.frame)
        self.label_36.setGeometry(QtCore.QRect(10, 210, 151, 31))
        self.label_36.setObjectName("label_36")
        self.licensenumber = QtWidgets.QLineEdit(self.frame)
        self.licensenumber.setGeometry(QtCore.QRect(190, 60, 181, 31))
        self.licensenumber.setAutoFillBackground(False)
        self.licensenumber.setObjectName("licensenumber")
        self.label_37 = QtWidgets.QLabel(self.frame)
        self.label_37.setGeometry(QtCore.QRect(10, 330, 161, 21))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.frame)
        self.label_38.setGeometry(QtCore.QRect(400, 180, 151, 31))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.frame)
        self.label_39.setGeometry(QtCore.QRect(10, 100, 101, 21))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.frame)
        self.label_40.setGeometry(QtCore.QRect(10, 260, 91, 21))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.frame)
        self.label_41.setGeometry(QtCore.QRect(390, 140, 181, 31))
        self.label_41.setObjectName("label_41")
        self.carmake = QtWidgets.QLineEdit(self.frame)
        self.carmake.setGeometry(QtCore.QRect(190, 260, 181, 31))
        self.carmake.setAutoFillBackground(False)
        self.carmake.setObjectName("carmake")
        self.cartype = QtWidgets.QLineEdit(self.frame)
        self.cartype.setGeometry(QtCore.QRect(190, 300, 181, 31))
        self.cartype.setAutoFillBackground(False)
        self.cartype.setObjectName("cartype")
        self.chasisnumber = QtWidgets.QLineEdit(self.frame)
        self.chasisnumber.setGeometry(QtCore.QRect(190, 340, 181, 31))
        self.chasisnumber.setObjectName("chasisnumber")
        self.carmodel = QtWidgets.QLineEdit(self.frame)
        self.carmodel.setGeometry(QtCore.QRect(190, 100, 181, 31))
        self.carmodel.setAutoFillBackground(False)
        self.carmodel.setObjectName("carmodel")
        self.mainstack.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_42 = QtWidgets.QLabel(self.page_5)
        self.label_42.setGeometry(QtCore.QRect(320, 80, 261, 41))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.page_5)
        self.label_43.setGeometry(QtCore.QRect(230, 160, 161, 41))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.page_5)
        self.label_44.setGeometry(QtCore.QRect(230, 220, 121, 41))
        self.label_44.setObjectName("label_44")
        self.loginusername = QtWidgets.QLineEdit(self.page_5)
        self.loginusername.setGeometry(QtCore.QRect(390, 160, 171, 41))
        self.loginusername.setObjectName("loginusername")
        self.loginpassword = QtWidgets.QLineEdit(self.page_5)
        self.loginpassword.setGeometry(QtCore.QRect(390, 220, 171, 41))
        self.loginpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.loginpassword.setObjectName("loginpassword")
        self.loginbutton = QtWidgets.QPushButton(self.page_5)
        self.loginbutton.setGeometry(QtCore.QRect(230, 310, 121, 41))
        self.loginbutton.setObjectName("loginbutton")
        self.createaccountbutton = QtWidgets.QPushButton(self.page_5)
        self.createaccountbutton.setGeometry(QtCore.QRect(370, 310, 151, 41))
        self.createaccountbutton.setObjectName("createaccountbutton")
        self.mainstack.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_45 = QtWidgets.QLabel(self.page_6)
        self.label_45.setGeometry(QtCore.QRect(190, 130, 131, 21))
        self.label_45.setObjectName("label_45")
        self.carnumber = QtWidgets.QLineEdit(self.page_6)
        self.carnumber.setGeometry(QtCore.QRect(370, 220, 181, 31))
        self.carnumber.setObjectName("carnumber")
        self.fuelnumber = QtWidgets.QLineEdit(self.page_6)
        self.fuelnumber.setGeometry(QtCore.QRect(370, 120, 181, 31))
        self.fuelnumber.setObjectName("fuelnumber")
        self.label_46 = QtWidgets.QLabel(self.page_6)
        self.label_46.setGeometry(QtCore.QRect(190, 220, 141, 21))
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.page_6)
        self.label_47.setGeometry(QtCore.QRect(190, 170, 121, 31))
        self.label_47.setObjectName("label_47")
        self.givefuel = QtWidgets.QPushButton(self.page_6)
        self.givefuel.setGeometry(QtCore.QRect(290, 280, 131, 31))
        self.givefuel.setObjectName("givefuel")
        self.label_48 = QtWidgets.QLabel(self.page_6)
        self.label_48.setGeometry(QtCore.QRect(300, 70, 171, 21))
        self.label_48.setObjectName("label_48")
        self.drivernumber = QtWidgets.QLineEdit(self.page_6)
        self.drivernumber.setGeometry(QtCore.QRect(370, 170, 181, 31))
        self.drivernumber.setObjectName("drivernumber")
        self.mainstack.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.drivernumserv_2 = QtWidgets.QLineEdit(self.page_7)
        self.drivernumserv_2.setGeometry(QtCore.QRect(410, 100, 181, 31))
        self.drivernumserv_2.setObjectName("drivernumserv_2")
        self.label_49 = QtWidgets.QLabel(self.page_7)
        self.label_49.setGeometry(QtCore.QRect(230, 110, 131, 21))
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.page_7)
        self.label_50.setGeometry(QtCore.QRect(230, 410, 131, 21))
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.page_7)
        self.label_51.setGeometry(QtCore.QRect(230, 180, 131, 31))
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.page_7)
        self.label_52.setGeometry(QtCore.QRect(230, 260, 141, 31))
        self.label_52.setObjectName("label_52")
        self.servicetype_2 = QtWidgets.QLineEdit(self.page_7)
        self.servicetype_2.setGeometry(QtCore.QRect(410, 140, 181, 31))
        self.servicetype_2.setObjectName("servicetype_2")
        self.partsservice_2 = QtWidgets.QTextEdit(self.page_7)
        self.partsservice_2.setGeometry(QtCore.QRect(410, 180, 181, 71))
        self.partsservice_2.setObjectName("partsservice_2")
        self.submitservice_2 = QtWidgets.QPushButton(self.page_7)
        self.submitservice_2.setGeometry(QtCore.QRect(340, 460, 131, 31))
        self.submitservice_2.setObjectName("submitservice_2")
        self.dateservice_2 = QtWidgets.QDateEdit(self.page_7)
        self.dateservice_2.setGeometry(QtCore.QRect(410, 260, 181, 31))
        self.dateservice_2.setObjectName("dateservice_2")
        self.servicedescription_2 = QtWidgets.QTextEdit(self.page_7)
        self.servicedescription_2.setGeometry(QtCore.QRect(410, 300, 181, 101))
        self.servicedescription_2.setObjectName("servicedescription_2")
        self.label_53 = QtWidgets.QLabel(self.page_7)
        self.label_53.setGeometry(QtCore.QRect(230, 140, 141, 31))
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.page_7)
        self.label_54.setGeometry(QtCore.QRect(230, 65, 171, 21))
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.page_7)
        self.label_55.setGeometry(QtCore.QRect(230, 330, 141, 31))
        self.label_55.setObjectName("label_55")
        self.numcarserv_2 = QtWidgets.QLineEdit(self.page_7)
        self.numcarserv_2.setGeometry(QtCore.QRect(410, 60, 181, 31))
        self.numcarserv_2.setObjectName("numcarserv_2")
        self.label_56 = QtWidgets.QLabel(self.page_7)
        self.label_56.setGeometry(QtCore.QRect(305, 30, 131, 20))
        self.label_56.setObjectName("label_56")
        self.serviceinvoice_2 = QtWidgets.QLineEdit(self.page_7)
        self.serviceinvoice_2.setGeometry(QtCore.QRect(410, 420, 181, 31))
        self.serviceinvoice_2.setObjectName("serviceinvoice_2")
        self.mainstack.addWidget(self.page_7)
        self.verticalLayout.addWidget(self.mainstack)
        fleetx.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(fleetx)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuCars = QtWidgets.QMenu(self.menubar)
        self.menuCars.setObjectName("menuCars")
        self.menuDeployment = QtWidgets.QMenu(self.menubar)
        self.menuDeployment.setObjectName("menuDeployment")
        self.menuRepairs_Service = QtWidgets.QMenu(self.menubar)
        self.menuRepairs_Service.setObjectName("menuRepairs_Service")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuReports = QtWidgets.QMenu(self.menubar)
        self.menuReports.setObjectName("menuReports")
        self.fleetdeploymentweekly = QtWidgets.QMenu(self.menuReports)
        self.fleetdeploymentweekly.setObjectName("fleetdeploymentweekly")
        self.menuFuelage_reports = QtWidgets.QMenu(self.menuReports)
        self.menuFuelage_reports.setObjectName("menuFuelage_reports")
        self.menuMileage_reports = QtWidgets.QMenu(self.menuReports)
        self.menuMileage_reports.setObjectName("menuMileage_reports")
        self.menuAccident_reports = QtWidgets.QMenu(self.menuReports)
        self.menuAccident_reports.setObjectName("menuAccident_reports")
        self.menuRepair_reports = QtWidgets.QMenu(self.menuReports)
        self.menuRepair_reports.setObjectName("menuRepair_reports")
        self.menuDriver_reports = QtWidgets.QMenu(self.menuReports)
        self.menuDriver_reports.setObjectName("menuDriver_reports")
        self.menuUncertainities = QtWidgets.QMenu(self.menubar)
        self.menuUncertainities.setObjectName("menuUncertainities")
        fleetx.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(fleetx)
        self.toolBar.setMovable(True)
        self.toolBar.setObjectName("toolBar")
        fleetx.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.fleetexit = QtWidgets.QAction(fleetx)
        self.fleetexit.setObjectName("fleetexit")
        self.fleetclose = QtWidgets.QAction(fleetx)
        self.fleetclose.setObjectName("fleetclose")
        self.fleetlogout = QtWidgets.QAction(fleetx)
        self.fleetlogout.setObjectName("fleetlogout")
        self.fleetaddcar = QtWidgets.QAction(fleetx)
        self.fleetaddcar.setObjectName("fleetaddcar")
        self.fleetviewcar = QtWidgets.QAction(fleetx)
        self.fleetviewcar.setObjectName("fleetviewcar")
        self.fleetdeploycar = QtWidgets.QAction(fleetx)
        self.fleetdeploycar.setObjectName("fleetdeploycar")
        self.fleetcardetails = QtWidgets.QAction(fleetx)
        self.fleetcardetails.setObjectName("fleetcardetails")
        self.fleetcaranalysis = QtWidgets.QAction(fleetx)
        self.fleetcaranalysis.setObjectName("fleetcaranalysis")
        self.fleetservices = QtWidgets.QAction(fleetx)
        self.fleetservices.setObjectName("fleetservices")
        self.fleetrepair = QtWidgets.QAction(fleetx)
        self.fleetrepair.setObjectName("fleetrepair")
        self.fleetfluage = QtWidgets.QAction(fleetx)
        self.fleetfluage.setObjectName("fleetfluage")
        self.fleetremovecar = QtWidgets.QAction(fleetx)
        self.fleetremovecar.setObjectName("fleetremovecar")
        self.fleetadddrive = QtWidgets.QAction(fleetx)
        self.fleetadddrive.setObjectName("fleetadddrive")
        self.fleetremovedriver = QtWidgets.QAction(fleetx)
        self.fleetremovedriver.setObjectName("fleetremovedriver")
        self.fleetanalysedrive = QtWidgets.QAction(fleetx)
        self.fleetanalysedrive.setObjectName("fleetanalysedrive")
        self.fleetdeploydrive = QtWidgets.QAction(fleetx)
        self.fleetdeploydrive.setObjectName("fleetdeploydrive")
        self.fleetcarwithdraw = QtWidgets.QAction(fleetx)
        self.fleetcarwithdraw.setObjectName("fleetcarwithdraw")
        self.deploymentweekly = QtWidgets.QAction(fleetx)
        self.deploymentweekly.setObjectName("deploymentweekly")
        self.deploymentmonthly = QtWidgets.QAction(fleetx)
        self.deploymentmonthly.setObjectName("deploymentmonthly")
        self.deploymentannually = QtWidgets.QAction(fleetx)
        self.deploymentannually.setObjectName("deploymentannually")
        self.fuelageweekly = QtWidgets.QAction(fleetx)
        self.fuelageweekly.setObjectName("fuelageweekly")
        self.fuelagemonthly = QtWidgets.QAction(fleetx)
        self.fuelagemonthly.setObjectName("fuelagemonthly")
        self.fuelageannually = QtWidgets.QAction(fleetx)
        self.fuelageannually.setObjectName("fuelageannually")
        self.mileageweekly = QtWidgets.QAction(fleetx)
        self.mileageweekly.setObjectName("mileageweekly")
        self.mileagemonthly = QtWidgets.QAction(fleetx)
        self.mileagemonthly.setObjectName("mileagemonthly")
        self.mileageannually = QtWidgets.QAction(fleetx)
        self.mileageannually.setObjectName("mileageannually")
        self.accidentweekly = QtWidgets.QAction(fleetx)
        self.accidentweekly.setObjectName("accidentweekly")
        self.accidentmonthly = QtWidgets.QAction(fleetx)
        self.accidentmonthly.setObjectName("accidentmonthly")
        self.accidentannually = QtWidgets.QAction(fleetx)
        self.accidentannually.setObjectName("accidentannually")
        self.repairweekly = QtWidgets.QAction(fleetx)
        self.repairweekly.setObjectName("repairweekly")
        self.repairmonthly = QtWidgets.QAction(fleetx)
        self.repairmonthly.setObjectName("repairmonthly")
        self.repairannually = QtWidgets.QAction(fleetx)
        self.repairannually.setObjectName("repairannually")
        self.driverweekly = QtWidgets.QAction(fleetx)
        self.driverweekly.setObjectName("driverweekly")
        self.drivemonthly = QtWidgets.QAction(fleetx)
        self.drivemonthly.setObjectName("drivemonthly")
        self.driveannually = QtWidgets.QAction(fleetx)
        self.driveannually.setObjectName("driveannually")
        self.fleeteditcardetails = QtWidgets.QAction(fleetx)
        self.fleeteditcardetails.setObjectName("fleeteditcardetails")
        self.fleeteditdrivedetails = QtWidgets.QAction(fleetx)
        self.fleeteditdrivedetails.setObjectName("fleeteditdrivedetails")
        self.actionAccidents = QtWidgets.QAction(fleetx)
        self.actionAccidents.setObjectName("actionAccidents")
        self.fleettheft = QtWidgets.QAction(fleetx)
        self.fleettheft.setObjectName("fleettheft")
        self.fleetmisplacement = QtWidgets.QAction(fleetx)
        self.fleetmisplacement.setObjectName("fleetmisplacement")
        self.fleetcompersation = QtWidgets.QAction(fleetx)
        self.fleetcompersation.setObjectName("fleetcompersation")
        self.fleetaccident = QtWidgets.QAction(fleetx)
        self.fleetaccident.setObjectName("fleetaccident")
        self.menuFile.addAction(self.fleetexit)
        self.menuFile.addAction(self.fleetclose)
        self.menuFile.addAction(self.fleetlogout)
        self.menuCars.addAction(self.fleetaddcar)
        self.menuCars.addAction(self.fleetviewcar)
        self.menuCars.addAction(self.fleetdeploycar)
        self.menuCars.addAction(self.fleetcardetails)
        self.menuCars.addAction(self.fleetcaranalysis)
        self.menuCars.addAction(self.fleetremovecar)
        self.menuCars.addAction(self.fleeteditcardetails)
        self.menuDeployment.addAction(self.fleetadddrive)
        self.menuDeployment.addAction(self.fleetremovedriver)
        self.menuDeployment.addAction(self.fleetanalysedrive)
        self.menuDeployment.addAction(self.fleetdeploydrive)
        self.menuDeployment.addAction(self.fleeteditdrivedetails)
        self.menuRepairs_Service.addAction(self.fleetservices)
        self.menuRepairs_Service.addAction(self.fleetrepair)
        self.menuRepairs_Service.addAction(self.fleetfluage)
        self.menuRepairs_Service.addAction(self.fleetcarwithdraw)
        self.fleetdeploymentweekly.addAction(self.deploymentweekly)
        self.fleetdeploymentweekly.addAction(self.deploymentmonthly)
        self.fleetdeploymentweekly.addAction(self.deploymentannually)
        self.menuFuelage_reports.addAction(self.fuelageweekly)
        self.menuFuelage_reports.addAction(self.fuelagemonthly)
        self.menuFuelage_reports.addAction(self.fuelageannually)
        self.menuMileage_reports.addAction(self.mileageweekly)
        self.menuMileage_reports.addAction(self.mileagemonthly)
        self.menuMileage_reports.addAction(self.mileageannually)
        self.menuAccident_reports.addAction(self.accidentweekly)
        self.menuAccident_reports.addAction(self.accidentmonthly)
        self.menuAccident_reports.addAction(self.accidentannually)
        self.menuRepair_reports.addAction(self.repairweekly)
        self.menuRepair_reports.addAction(self.repairmonthly)
        self.menuRepair_reports.addAction(self.repairannually)
        self.menuDriver_reports.addAction(self.driverweekly)
        self.menuDriver_reports.addAction(self.drivemonthly)
        self.menuDriver_reports.addAction(self.driveannually)
        self.menuReports.addAction(self.fleetdeploymentweekly.menuAction())
        self.menuReports.addAction(self.menuFuelage_reports.menuAction())
        self.menuReports.addAction(self.menuMileage_reports.menuAction())
        self.menuReports.addAction(self.menuAccident_reports.menuAction())
        self.menuReports.addAction(self.menuRepair_reports.menuAction())
        self.menuReports.addAction(self.menuDriver_reports.menuAction())
        self.menuUncertainities.addAction(self.fleettheft)
        self.menuUncertainities.addAction(self.fleetmisplacement)
        self.menuUncertainities.addAction(self.fleetcompersation)
        self.menuUncertainities.addAction(self.fleetaccident)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCars.menuAction())
        self.menubar.addAction(self.menuDeployment.menuAction())
        self.menubar.addAction(self.menuRepairs_Service.menuAction())
        self.menubar.addAction(self.menuUncertainities.menuAction())
        self.menubar.addAction(self.menuReports.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.fleetdeploycar)
        self.toolBar.addAction(self.fleetcardetails)
        self.toolBar.addAction(self.fleetcaranalysis)
        self.toolBar.addAction(self.fleetdeploydrive)
        self.toolBar.addAction(self.fleetaccident)
        self.toolBar.addAction(self.fleetlogout)
        self.toolBar.addAction(self.fleetexit)

        self.retranslateUi(fleetx)
        self.mainstack.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(fleetx)

    def retranslateUi(self, fleetx):
        _translate = QtCore.QCoreApplication.translate
        fleetx.setWindowTitle(_translate("fleetx", "Fleet Man"))
        self.label_3.setText(_translate("fleetx", "Drive Number"))
        self.label_2.setText(_translate("fleetx", "Car Number"))
        self.label.setText(_translate("fleetx", "DEPLOY CAR"))
        self.pushButton.setText(_translate("fleetx", "Deploy Car"))
        self.label_6.setText(_translate("fleetx", "Destination"))
        self.label_5.setText(_translate("fleetx", "Fuel Card Number"))
        self.label_10.setText(_translate("fleetx", "Gender"))
        self.label_4.setText(_translate("fleetx", "Add Car"))
        self.female.setText(_translate("fleetx", "Female"))
        self.label_8.setText(_translate("fleetx", "Date of Birth"))
        self.label_7.setText(_translate("fleetx", "Permit Number"))
        self.label_9.setText(_translate("fleetx", "Permit Class"))
        self.label_11.setText(_translate("fleetx", "First Name"))
        self.label_12.setText(_translate("fleetx", "Photo"))
        self.label_13.setText(_translate("fleetx", "Last Name"))
        self.label_14.setText(_translate("fleetx", "Address"))
        self.label_15.setText(_translate("fleetx", "Email Address"))
        self.label_16.setText(_translate("fleetx", "Phone Number"))
        self.male.setText(_translate("fleetx", "Male"))
        self.pushButton_2.setText(_translate("fleetx", "Add Driver"))
        self.label_17.setText(_translate("fleetx", "Service Type"))
        self.label_18.setText(_translate("fleetx", "Parts affected"))
        self.label_19.setText(_translate("fleetx", "Car licence plate number"))
        self.label_20.setText(_translate("fleetx", "Date of Service"))
        self.label_21.setText(_translate("fleetx", "Enter repair details"))
        self.label_22.setText(_translate("fleetx", "Service Description"))
        self.label_23.setText(_translate("fleetx", "Driver Number"))
        self.label_24.setText(_translate("fleetx", "Invoice Image"))
        self.submitservice.setText(_translate("fleetx", "Submit Details"))
        self.label_57.setText(_translate("fleetx", "Car Report"))
        item = self.carreport.horizontalHeaderItem(0)
        item.setText(_translate("fleetx", "Car Licence Number"))
        item = self.carreport.horizontalHeaderItem(1)
        item.setText(_translate("fleetx", "Type"))
        item = self.carreport.horizontalHeaderItem(2)
        item.setText(_translate("fleetx", "Fuelage"))
        item = self.carreport.horizontalHeaderItem(3)
        item.setText(_translate("fleetx", "Mileage"))
        item = self.carreport.horizontalHeaderItem(4)
        item.setText(_translate("fleetx", "Accident Case"))
        item = self.carreport.horizontalHeaderItem(5)
        item.setText(_translate("fleetx", "Service Case"))
        item = self.drivelist.horizontalHeaderItem(0)
        item.setText(_translate("fleetx", "First Name"))
        item = self.drivelist.horizontalHeaderItem(1)
        item.setText(_translate("fleetx", "Second Name"))
        item = self.drivelist.horizontalHeaderItem(2)
        item.setText(_translate("fleetx", "Age"))
        item = self.drivelist.horizontalHeaderItem(3)
        item.setText(_translate("fleetx", "Phone"))
        item = self.drivelist.horizontalHeaderItem(4)
        item.setText(_translate("fleetx", "Fuelage"))
        self.label_25.setText(_translate("fleetx", "Type"))
        self.label_27.setText(_translate("fleetx", "License plate number"))
        self.fuel_type.setItemText(0, _translate("fleetx", "Petrol"))
        self.fuel_type.setItemText(1, _translate("fleetx", "Deisel"))
        self.label_28.setText(_translate("fleetx", "Color"))
        self.label_29.setText(_translate("fleetx", "Fuel Type"))
        self.label_30.setText(_translate("fleetx", "Left Side Photo"))
        self.label_31.setText(_translate("fleetx", "ADD CAR DETAILS"))
        self.label_32.setText(_translate("fleetx", "Manufacture Date"))
        self.InsuranceCompany.setText(_translate("fleetx", "Insurance Company"))
        self.addcar.setText(_translate("fleetx", "Add Car"))
        self.label_33.setText(_translate("fleetx", "Right Side Photo"))
        self.label_34.setText(_translate("fleetx", "Front Photo"))
        self.label_35.setText(_translate("fleetx", "Behind Photo"))
        self.label_36.setText(_translate("fleetx", "Mileage"))
        self.label_37.setText(_translate("fleetx", "Chasis Number"))
        self.label_38.setText(_translate("fleetx", "3rd party expiry date"))
        self.label_39.setText(_translate("fleetx", "Car Model"))
        self.label_40.setText(_translate("fleetx", "Make"))
        self.label_41.setText(_translate("fleetx", "3rd Party Subscpriton date"))
        self.label_42.setText(_translate("fleetx", "Welcome to FleetX please login here"))
        self.label_43.setText(_translate("fleetx", "Username"))
        self.label_44.setText(_translate("fleetx", "Password"))
        self.loginbutton.setText(_translate("fleetx", "Login"))
        self.createaccountbutton.setText(_translate("fleetx", "Creat Account"))
        self.label_45.setText(_translate("fleetx", "Fuel Card Number"))
        self.label_46.setText(_translate("fleetx", "Car Licence Number"))
        self.label_47.setText(_translate("fleetx", "Driver Number"))
        self.givefuel.setText(_translate("fleetx", "Submit Details"))
        self.label_48.setText(_translate("fleetx", "Fueling Service"))
        self.label_49.setText(_translate("fleetx", "Driver Number"))
        self.label_50.setText(_translate("fleetx", "Invoice Image"))
        self.label_51.setText(_translate("fleetx", "Parts affectes"))
        self.label_52.setText(_translate("fleetx", "Date of Service"))
        self.submitservice_2.setText(_translate("fleetx", "Submit Details"))
        self.label_53.setText(_translate("fleetx", "Service Type"))
        self.label_54.setText(_translate("fleetx", "Car licence plate number"))
        self.label_55.setText(_translate("fleetx", "Service Description"))
        self.label_56.setText(_translate("fleetx", "Enter repair details"))
        self.menuFile.setTitle(_translate("fleetx", "File"))
        self.menuCars.setTitle(_translate("fleetx", "Cars"))
        self.menuDeployment.setTitle(_translate("fleetx", "Driver"))
        self.menuRepairs_Service.setTitle(_translate("fleetx", "Maintenances"))
        self.menuSettings.setTitle(_translate("fleetx", "Settings"))
        self.menuHelp.setTitle(_translate("fleetx", "Help"))
        self.menuReports.setTitle(_translate("fleetx", "Reports"))
        self.fleetdeploymentweekly.setTitle(_translate("fleetx", "Deployment reports"))
        self.menuFuelage_reports.setTitle(_translate("fleetx", "Fuelage reports"))
        self.menuMileage_reports.setTitle(_translate("fleetx", "Mileage reports"))
        self.menuAccident_reports.setTitle(_translate("fleetx", "Accident reports"))
        self.menuRepair_reports.setTitle(_translate("fleetx", "Repair reports"))
        self.menuDriver_reports.setTitle(_translate("fleetx", "Driver reports"))
        self.menuUncertainities.setTitle(_translate("fleetx", "Uncertainities"))
        self.toolBar.setWindowTitle(_translate("fleetx", "toolBar"))
        self.fleetexit.setText(_translate("fleetx", "Exit"))
        self.fleetclose.setText(_translate("fleetx", "Close"))
        self.fleetlogout.setText(_translate("fleetx", "Logout"))
        self.fleetaddcar.setText(_translate("fleetx", "Add Car"))
        self.fleetviewcar.setText(_translate("fleetx", "View Cars"))
        self.fleetdeploycar.setText(_translate("fleetx", "Deploy car"))
        self.fleetcardetails.setText(_translate("fleetx", "Car Details"))
        self.fleetcaranalysis.setText(_translate("fleetx", "Cars analysis"))
        self.fleetservices.setText(_translate("fleetx", "Services"))
        self.fleetrepair.setText(_translate("fleetx", "Repair"))
        self.fleetfluage.setText(_translate("fleetx", "Fuelage"))
        self.fleetremovecar.setText(_translate("fleetx", "Remove car"))
        self.fleetadddrive.setText(_translate("fleetx", "Add driver"))
        self.fleetremovedriver.setText(_translate("fleetx", "Remove driver"))
        self.fleetanalysedrive.setText(_translate("fleetx", "Analyse Driver"))
        self.fleetdeploydrive.setText(_translate("fleetx", "Deploy driver"))
        self.fleetcarwithdraw.setText(_translate("fleetx", "Car withdraw"))
        self.deploymentweekly.setText(_translate("fleetx", "Weekly"))
        self.deploymentmonthly.setText(_translate("fleetx", "Monthly"))
        self.deploymentannually.setText(_translate("fleetx", "Annual"))
        self.fuelageweekly.setText(_translate("fleetx", "Weekly"))
        self.fuelagemonthly.setText(_translate("fleetx", "Monthly"))
        self.fuelageannually.setText(_translate("fleetx", "Annual"))
        self.mileageweekly.setText(_translate("fleetx", "Weekly"))
        self.mileagemonthly.setText(_translate("fleetx", "Monthly"))
        self.mileageannually.setText(_translate("fleetx", "Annual"))
        self.accidentweekly.setText(_translate("fleetx", "Weekly"))
        self.accidentmonthly.setText(_translate("fleetx", "Monthly"))
        self.accidentannually.setText(_translate("fleetx", "Annual"))
        self.repairweekly.setText(_translate("fleetx", "Weekly"))
        self.repairmonthly.setText(_translate("fleetx", "Monthly"))
        self.repairannually.setText(_translate("fleetx", "Annual"))
        self.driverweekly.setText(_translate("fleetx", "Weekly"))
        self.drivemonthly.setText(_translate("fleetx", "Monthly"))
        self.driveannually.setText(_translate("fleetx", "Annual"))
        self.fleeteditcardetails.setText(_translate("fleetx", "Edit Car details"))
        self.fleeteditdrivedetails.setText(_translate("fleetx", "Edit driver details"))
        self.actionAccidents.setText(_translate("fleetx", "Accidents"))
        self.fleettheft.setText(_translate("fleetx", "Theft"))
        self.fleetmisplacement.setText(_translate("fleetx", "Misplacement"))
        self.fleetcompersation.setText(_translate("fleetx", "Compasation"))
        self.fleetaccident.setText(_translate("fleetx", "Accident Event"))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fleetx = QtWidgets.QMainWindow()
    ui = Ui_fleetx()
    ui.setupUi(fleetx)
    fleetx.show()
    sys.exit(app.exec_())

