# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainfleetx.ui'
#
# Created: Fri Sep 22 00:22:08 2017
#      by: PyQt5 UI code generator 5.3.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainfleet(object):
    def setupUi(self, mainfleet):
        mainfleet.setObjectName("mainfleet")
        mainfleet.resize(915, 619)
        mainfleet.setAutoFillBackground(True)
        mainfleet.setStyleSheet("QTabWidget{\n"
"background-color:#00bfff; color:red; border:0px;\n"
"}\n"
"QTreeWidget{\n"
"background-color:#fffafa; font-size:15px; border:0px;\n"
"}\n"
"QTreeWidget::item::selected{\n"
"color:#ffffff;\n"
"}\n"
"QTableWidget{\n"
"border:0px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(mainfleet)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainstackwidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.mainstackwidget.setObjectName("mainstackwidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.page)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.carswidget_2 = QtWidgets.QTableWidget(self.tab)
        self.carswidget_2.setObjectName("carswidget_2")
        self.carswidget_2.setColumnCount(0)
        self.carswidget_2.setRowCount(0)
        self.horizontalLayout_3.addWidget(self.carswidget_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.mainstackwidget.addWidget(self.page)
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.deploymentwidget = QtWidgets.QTabWidget(self.widget)
        self.deploymentwidget.setObjectName("deploymentwidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.deploymentwidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.deploymentwidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.deploymentwidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.deploymentwidget.addTab(self.tab_6, "")
        self.horizontalLayout_4.addWidget(self.deploymentwidget)
        self.mainstackwidget.addWidget(self.widget)
        self.widget1 = QtWidgets.QWidget()
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.carswidget = QtWidgets.QTabWidget(self.widget1)
        self.carswidget.setObjectName("carswidget")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.tab_7)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame = QtWidgets.QFrame(self.tab_7)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(310, 340, 131, 31))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(200, 160, 81, 31))
        self.label_2.setObjectName("label_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(350, 290, 171, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(350, 170, 171, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(350, 250, 171, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(200, 210, 121, 16))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(200, 290, 121, 21))
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(300, 130, 101, 16))
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(350, 210, 171, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(200, 250, 71, 16))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_14.addWidget(self.frame)
        self.carswidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.carswidget.addTab(self.tab_8, "")
        self.tab_18 = QtWidgets.QWidget()
        self.tab_18.setObjectName("tab_18")
        self.groupBox = QtWidgets.QGroupBox(self.tab_18)
        self.groupBox.setGeometry(QtCore.QRect(220, 100, 161, 181))
        self.groupBox.setObjectName("groupBox")
        self.carswidget.addTab(self.tab_18, "")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.carswidget.addTab(self.tab_17, "")
        self.tab_19 = QtWidgets.QWidget()
        self.tab_19.setObjectName("tab_19")
        self.carswidget.addTab(self.tab_19, "")
        self.horizontalLayout_5.addWidget(self.carswidget)
        self.mainstackwidget.addWidget(self.widget1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.driverdetails = QtWidgets.QTabWidget(self.page_2)
        self.driverdetails.setObjectName("driverdetails")
        self.alldriverstab = QtWidgets.QWidget()
        self.alldriverstab.setObjectName("alldriverstab")
        self.driverdetails.addTab(self.alldriverstab, "")
        self.deploydrivertab = QtWidgets.QWidget()
        self.deploydrivertab.setObjectName("deploydrivertab")
        self.driverdetails.addTab(self.deploydrivertab, "")
        self.driverdetailstab = QtWidgets.QWidget()
        self.driverdetailstab.setObjectName("driverdetailstab")
        self.driverdetails.addTab(self.driverdetailstab, "")
        self.adddrivertab = QtWidgets.QWidget()
        self.adddrivertab.setObjectName("adddrivertab")
        self.driverdetails.addTab(self.adddrivertab, "")
        self.editdrivertab = QtWidgets.QWidget()
        self.editdrivertab.setObjectName("editdrivertab")
        self.driverdetails.addTab(self.editdrivertab, "")
        self.removedrivetab = QtWidgets.QWidget()
        self.removedrivetab.setObjectName("removedrivetab")
        self.driverdetails.addTab(self.removedrivetab, "")
        self.horizontalLayout_6.addWidget(self.driverdetails)
        self.mainstackwidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.reporting = QtWidgets.QTabWidget(self.page_3)
        self.reporting.setObjectName("reporting")
        self.carreportstab = QtWidgets.QWidget()
        self.carreportstab.setObjectName("carreportstab")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.carreportstab)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tableWidget = QtWidgets.QTableWidget(self.carreportstab)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout_8.addWidget(self.tableWidget)
        self.reporting.addTab(self.carreportstab, "")
        self.driverreportstab = QtWidgets.QWidget()
        self.driverreportstab.setObjectName("driverreportstab")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.driverreportstab)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.driverreportstab)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.horizontalLayout_9.addWidget(self.tableWidget_2)
        self.reporting.addTab(self.driverreportstab, "")
        self.deploymentreportstab = QtWidgets.QWidget()
        self.deploymentreportstab.setObjectName("deploymentreportstab")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.deploymentreportstab)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.deploymentreportstab)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.horizontalLayout_10.addWidget(self.tableWidget_3)
        self.reporting.addTab(self.deploymentreportstab, "")
        self.servicereportstab = QtWidgets.QWidget()
        self.servicereportstab.setObjectName("servicereportstab")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.servicereportstab)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.servicereportstab)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(0)
        self.tableWidget_4.setRowCount(0)
        self.horizontalLayout_11.addWidget(self.tableWidget_4)
        self.reporting.addTab(self.servicereportstab, "")
        self.repairreportstab = QtWidgets.QWidget()
        self.repairreportstab.setObjectName("repairreportstab")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.repairreportstab)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.repairreportstab)
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(0)
        self.tableWidget_5.setRowCount(0)
        self.horizontalLayout_12.addWidget(self.tableWidget_5)
        self.reporting.addTab(self.repairreportstab, "")
        self.uncertainitiesreportstab = QtWidgets.QWidget()
        self.uncertainitiesreportstab.setObjectName("uncertainitiesreportstab")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.uncertainitiesreportstab)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.uncertainitiesreportstab)
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(0)
        self.tableWidget_6.setRowCount(0)
        self.horizontalLayout_13.addWidget(self.tableWidget_6)
        self.reporting.addTab(self.uncertainitiesreportstab, "")
        self.horizontalLayout_7.addWidget(self.reporting)
        self.mainstackwidget.addWidget(self.page_3)
        self.horizontalLayout.addWidget(self.mainstackwidget)
        mainfleet.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainfleet)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 915, 21))
        self.menubar.setObjectName("menubar")
        self.menuCars = QtWidgets.QMenu(self.menubar)
        self.menuCars.setObjectName("menuCars")
        self.menuDrivers = QtWidgets.QMenu(self.menubar)
        self.menuDrivers.setObjectName("menuDrivers")
        self.menuDeployments = QtWidgets.QMenu(self.menubar)
        self.menuDeployments.setObjectName("menuDeployments")
        self.menuUncertainities = QtWidgets.QMenu(self.menubar)
        self.menuUncertainities.setObjectName("menuUncertainities")
        self.menuReports = QtWidgets.QMenu(self.menubar)
        self.menuReports.setObjectName("menuReports")
        self.menuUser_Details = QtWidgets.QMenu(self.menubar)
        self.menuUser_Details.setObjectName("menuUser_Details")
        self.menuAbout_the_App = QtWidgets.QMenu(self.menubar)
        self.menuAbout_the_App.setObjectName("menuAbout_the_App")
        mainfleet.setMenuBar(self.menubar)
        self.All_Cars = QtWidgets.QAction(mainfleet)
        self.All_Cars.setObjectName("All_Cars")
        self.Deploy_Car = QtWidgets.QAction(mainfleet)
        self.Deploy_Car.setObjectName("Deploy_Car")
        self.Edit_Car = QtWidgets.QAction(mainfleet)
        self.Edit_Car.setObjectName("Edit_Car")
        self.Add_Car = QtWidgets.QAction(mainfleet)
        self.Add_Car.setObjectName("Add_Car")
        self.Remove_Car = QtWidgets.QAction(mainfleet)
        self.Remove_Car.setObjectName("Remove_Car")
        self.All_Drivers = QtWidgets.QAction(mainfleet)
        self.All_Drivers.setObjectName("All_Drivers")
        self.Deploy_Driver = QtWidgets.QAction(mainfleet)
        self.Deploy_Driver.setObjectName("Deploy_Driver")
        self.Edit_Driver = QtWidgets.QAction(mainfleet)
        self.Edit_Driver.setObjectName("Edit_Driver")
        self.Add_Driver = QtWidgets.QAction(mainfleet)
        self.Add_Driver.setObjectName("Add_Driver")
        self.Remove_Driver = QtWidgets.QAction(mainfleet)
        self.Remove_Driver.setObjectName("Remove_Driver")
        self.actionClose = QtWidgets.QAction(mainfleet)
        self.actionClose.setObjectName("actionClose")
        self.menuCars.addAction(self.All_Cars)
        self.menuCars.addAction(self.Deploy_Car)
        self.menuCars.addAction(self.Edit_Car)
        self.menuCars.addAction(self.Add_Car)
        self.menuCars.addAction(self.Remove_Car)
        self.menuCars.addAction(self.actionClose)
        self.menuDrivers.addAction(self.All_Drivers)
        self.menuDrivers.addAction(self.Deploy_Driver)
        self.menuDrivers.addAction(self.Edit_Driver)
        self.menuDrivers.addAction(self.Add_Driver)
        self.menuDrivers.addAction(self.Remove_Driver)
        self.menubar.addAction(self.menuCars.menuAction())
        self.menubar.addAction(self.menuDrivers.menuAction())
        self.menubar.addAction(self.menuDeployments.menuAction())
        self.menubar.addAction(self.menuUncertainities.menuAction())
        self.menubar.addAction(self.menuReports.menuAction())
        self.menubar.addAction(self.menuUser_Details.menuAction())
        self.menubar.addAction(self.menuAbout_the_App.menuAction())

        self.retranslateUi(mainfleet)
        self.mainstackwidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.deploymentwidget.setCurrentIndex(1)
        self.carswidget.setCurrentIndex(1)
        self.driverdetails.setCurrentIndex(5)
        self.reporting.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(mainfleet)

    def retranslateUi(self, mainfleet):
        _translate = QtCore.QCoreApplication.translate
        mainfleet.setWindowTitle(_translate("mainfleet", "FleetX"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainfleet", "All Cars"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainfleet", "Deployed Cars"))
        self.deploymentwidget.setTabText(self.deploymentwidget.indexOf(self.tab_3), _translate("mainfleet", "Deploy Employ"))
        self.deploymentwidget.setTabText(self.deploymentwidget.indexOf(self.tab_4), _translate("mainfleet", "Deployed Employes"))
        self.deploymentwidget.setTabText(self.deploymentwidget.indexOf(self.tab_5), _translate("mainfleet", "All Employees"))
        self.deploymentwidget.setTabText(self.deploymentwidget.indexOf(self.tab_6), _translate("mainfleet", "Add Employ"))
        self.pushButton.setText(_translate("mainfleet", "Deploy Car"))
        self.label_2.setText(_translate("mainfleet", "Car Number"))
        self.label_3.setText(_translate("mainfleet", "Drive Number"))
        self.label_5.setText(_translate("mainfleet", "Fuel Card Number"))
        self.label.setText(_translate("mainfleet", "DEPLOY CAR"))
        self.label_6.setText(_translate("mainfleet", "Destination"))
        self.carswidget.setTabText(self.carswidget.indexOf(self.tab_7), _translate("mainfleet", "Deploy Car"))
        self.carswidget.setTabText(self.carswidget.indexOf(self.tab_8), _translate("mainfleet", "Deployed Cars"))
        self.groupBox.setTitle(_translate("mainfleet", "GroupBox"))
        self.carswidget.setTabText(self.carswidget.indexOf(self.tab_18), _translate("mainfleet", "Edit Car"))
        self.carswidget.setTabText(self.carswidget.indexOf(self.tab_17), _translate("mainfleet", "Add Car"))
        self.carswidget.setTabText(self.carswidget.indexOf(self.tab_19), _translate("mainfleet", "Remove Car"))
        self.driverdetails.setTabText(self.driverdetails.indexOf(self.alldriverstab), _translate("mainfleet", "All Drivers"))
        self.driverdetails.setTabText(self.driverdetails.indexOf(self.deploydrivertab), _translate("mainfleet", "Deployed Drivers"))
        self.driverdetails.setTabText(self.driverdetails.indexOf(self.driverdetailstab), _translate("mainfleet", "View Diver Details"))
        self.driverdetails.setTabText(self.driverdetails.indexOf(self.adddrivertab), _translate("mainfleet", "Add Driver"))
        self.driverdetails.setTabText(self.driverdetails.indexOf(self.editdrivertab), _translate("mainfleet", "Edit Driver"))
        self.driverdetails.setTabText(self.driverdetails.indexOf(self.removedrivetab), _translate("mainfleet", "Remove Driver"))
        self.reporting.setTabText(self.reporting.indexOf(self.carreportstab), _translate("mainfleet", "Car Reports"))
        self.reporting.setTabText(self.reporting.indexOf(self.driverreportstab), _translate("mainfleet", "Driver Reports"))
        self.reporting.setTabText(self.reporting.indexOf(self.deploymentreportstab), _translate("mainfleet", "Deployment Reports"))
        self.reporting.setTabText(self.reporting.indexOf(self.servicereportstab), _translate("mainfleet", "Service Reports"))
        self.reporting.setTabText(self.reporting.indexOf(self.repairreportstab), _translate("mainfleet", "Repair Reports"))
        self.reporting.setTabText(self.reporting.indexOf(self.uncertainitiesreportstab), _translate("mainfleet", "Uncertainity Reports"))
        self.menuCars.setTitle(_translate("mainfleet", "Cars"))
        self.menuDrivers.setTitle(_translate("mainfleet", "Drivers"))
        self.menuDeployments.setTitle(_translate("mainfleet", "Deployments"))
        self.menuUncertainities.setTitle(_translate("mainfleet", "Uncertainities"))
        self.menuReports.setTitle(_translate("mainfleet", "Reports"))
        self.menuUser_Details.setTitle(_translate("mainfleet", "User Details"))
        self.menuAbout_the_App.setTitle(_translate("mainfleet", "About the App"))
        self.All_Cars.setText(_translate("mainfleet", "All Cars"))
        self.Deploy_Car.setText(_translate("mainfleet", "Deploy Car"))
        self.Edit_Car.setText(_translate("mainfleet", "Edit Car"))
        self.Add_Car.setText(_translate("mainfleet", "Add Car"))
        self.Remove_Car.setText(_translate("mainfleet", "Remove Car"))
        self.All_Drivers.setText(_translate("mainfleet", "All Drivers"))
        self.Deploy_Driver.setText(_translate("mainfleet", "Deploy Driver"))
        self.Edit_Driver.setText(_translate("mainfleet", "Edit Driver"))
        self.Add_Driver.setText(_translate("mainfleet", "Add Driver"))
        self.Remove_Driver.setText(_translate("mainfleet", "Remove Driver"))
        self.actionClose.setText(_translate("mainfleet", "Close "))

