# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newxfleet.ui'
#
# Created: Sat Sep 23 02:01:00 2017
#      by: PyQt5 UI code generator 5.3.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FleetX(object):
    def setupUi(self, FleetX):
        FleetX.setObjectName("FleetX")
        FleetX.resize(969, 597)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/fleets.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FleetX.setWindowIcon(icon)
        FleetX.setStyleSheet("QTabWidget{\n"
"border:0px;\n"
"}\n"
"QTableWidget{\n"
"border:0px;\n"
"}\n"
"QLabel{\n"
"font-size:15px;\n"
"}\n"
"QLineEdit{\n"
"font-size:15px;\n"
"}\n"
"QPushButton{\n"
"font-size:15px;\n"
"\n"
"}\n"
"QToolButton{\n"
"font-size:15px;\n"
"}\n"
"QTabWidget.menutab{\n"
"background-color:red;\n"
"}\n"
"QMainWindow{\n"
"background-color:#ffffff;\n"
"}\n"
"QTabBar{\n"
"font-size:15px; border:0px; margin:0px;\n"
"}\n"
"QToolButton::clicked{\n"
"background-color:#00bfaf;\n"
"}\n"
"/*\n"
"QTabBar::tab::selected{\n"
"color:red; background-color:blue; border-radius:4px;\n"
"}*/")
        self.centralwidget = QtWidgets.QWidget(FleetX)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menutab = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menutab.sizePolicy().hasHeightForWidth())
        self.menutab.setSizePolicy(sizePolicy)
        self.menutab.setStyleSheet("")
        self.menutab.setObjectName("menutab")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.carsbutton = QtWidgets.QToolButton(self.tab_9)
        self.carsbutton.setGeometry(QtCore.QRect(0, 10, 121, 41))
        self.carsbutton.setCheckable(True)
        self.carsbutton.setChecked(False)
        self.carsbutton.setAutoExclusive(False)
        self.carsbutton.setObjectName("carsbutton")
        self.driversbutton = QtWidgets.QToolButton(self.tab_9)
        self.driversbutton.setGeometry(QtCore.QRect(0, 60, 121, 41))
        self.driversbutton.setCheckable(True)
        self.driversbutton.setObjectName("driversbutton")
        self.uncertainitybutton = QtWidgets.QToolButton(self.tab_9)
        self.uncertainitybutton.setGeometry(QtCore.QRect(0, 210, 121, 41))
        self.uncertainitybutton.setCheckable(True)
        self.uncertainitybutton.setObjectName("uncertainitybutton")
        self.reportbutton = QtWidgets.QToolButton(self.tab_9)
        self.reportbutton.setGeometry(QtCore.QRect(0, 260, 121, 41))
        self.reportbutton.setCheckable(True)
        self.reportbutton.setObjectName("reportbutton")
        self.userbutton = QtWidgets.QToolButton(self.tab_9)
        self.userbutton.setGeometry(QtCore.QRect(0, 310, 121, 41))
        self.userbutton.setCheckable(True)
        self.userbutton.setObjectName("userbutton")
        self.logoutbutton = QtWidgets.QToolButton(self.tab_9)
        self.logoutbutton.setGeometry(QtCore.QRect(0, 360, 121, 41))
        self.logoutbutton.setCheckable(True)
        self.logoutbutton.setObjectName("logoutbutton")
        self.maintenamcebutton = QtWidgets.QToolButton(self.tab_9)
        self.maintenamcebutton.setGeometry(QtCore.QRect(0, 160, 121, 41))
        self.maintenamcebutton.setCheckable(True)
        self.maintenamcebutton.setObjectName("maintenamcebutton")
        self.searchbutton = QtWidgets.QToolButton(self.tab_9)
        self.searchbutton.setGeometry(QtCore.QRect(0, 110, 121, 41))
        self.searchbutton.setCheckable(True)
        self.searchbutton.setObjectName("searchbutton")
        self.menutab.addTab(self.tab_9, "")
        self.horizontalLayout.addWidget(self.menutab)
        self.mainstackwidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.mainstackwidget.setObjectName("mainstackwidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.servicetab = QtWidgets.QTabWidget(self.page)
        self.servicetab.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.servicetab.setObjectName("servicetab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_36 = QtWidgets.QLabel(self.tab)
        self.label_36.setGeometry(QtCore.QRect(140, 320, 141, 31))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.tab)
        self.label_37.setGeometry(QtCore.QRect(140, 170, 131, 31))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.tab)
        self.label_38.setGeometry(QtCore.QRect(140, 250, 141, 31))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.tab)
        self.label_39.setGeometry(QtCore.QRect(215, 20, 211, 20))
        self.label_39.setObjectName("label_39")
        self.partsservice = QtWidgets.QTextEdit(self.tab)
        self.partsservice.setGeometry(QtCore.QRect(320, 170, 181, 71))
        self.partsservice.setObjectName("partsservice")
        self.submitservice = QtWidgets.QPushButton(self.tab)
        self.submitservice.setGeometry(QtCore.QRect(250, 450, 131, 31))
        self.submitservice.setObjectName("submitservice")
        self.drivernumserv = QtWidgets.QLineEdit(self.tab)
        self.drivernumserv.setGeometry(QtCore.QRect(320, 90, 181, 31))
        self.drivernumserv.setObjectName("drivernumserv")
        self.label_40 = QtWidgets.QLabel(self.tab)
        self.label_40.setGeometry(QtCore.QRect(140, 400, 131, 21))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.tab)
        self.label_41.setGeometry(QtCore.QRect(140, 130, 141, 31))
        self.label_41.setObjectName("label_41")
        self.numcarserv = QtWidgets.QLineEdit(self.tab)
        self.numcarserv.setGeometry(QtCore.QRect(320, 50, 181, 31))
        self.numcarserv.setObjectName("numcarserv")
        self.label_42 = QtWidgets.QLabel(self.tab)
        self.label_42.setGeometry(QtCore.QRect(140, 55, 171, 21))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.tab)
        self.label_43.setGeometry(QtCore.QRect(140, 100, 131, 21))
        self.label_43.setObjectName("label_43")
        self.dateservice = QtWidgets.QDateEdit(self.tab)
        self.dateservice.setGeometry(QtCore.QRect(320, 250, 181, 31))
        self.dateservice.setObjectName("dateservice")
        self.servicedescription = QtWidgets.QTextEdit(self.tab)
        self.servicedescription.setGeometry(QtCore.QRect(320, 290, 181, 101))
        self.servicedescription.setObjectName("servicedescription")
        self.serviceinvoice = QtWidgets.QLineEdit(self.tab)
        self.serviceinvoice.setGeometry(QtCore.QRect(320, 410, 181, 31))
        self.serviceinvoice.setObjectName("serviceinvoice")
        self.servicebox = QtWidgets.QComboBox(self.tab)
        self.servicebox.setGeometry(QtCore.QRect(320, 130, 181, 31))
        self.servicebox.setObjectName("servicebox")
        self.servicebox.addItem("")
        self.servicebox.addItem("")
        self.servicetab.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.servicetab.addTab(self.tab_2, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_11)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableWidget_7 = QtWidgets.QTableWidget(self.tab_11)
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(4)
        self.tableWidget_7.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(3, item)
        self.horizontalLayout_3.addWidget(self.tableWidget_7)
        self.servicetab.addTab(self.tab_11, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.servicetab.addTab(self.tab_13, "")
        self.horizontalLayout_2.addWidget(self.servicetab)
        self.mainstackwidget.addWidget(self.page)
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.deploymentwidget = QtWidgets.QTabWidget(self.widget)
        self.deploymentwidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.deploymentwidget.setObjectName("deploymentwidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.deployeddriverstable = QtWidgets.QTableWidget(self.tab_4)
        self.deployeddriverstable.setAutoFillBackground(True)
        self.deployeddriverstable.setAutoScroll(True)
        self.deployeddriverstable.setAutoScrollMargin(0)
        self.deployeddriverstable.setTextElideMode(QtCore.Qt.ElideLeft)
        self.deployeddriverstable.setObjectName("deployeddriverstable")
        self.deployeddriverstable.setColumnCount(8)
        self.deployeddriverstable.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.deployeddriverstable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.deployeddriverstable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.deployeddriverstable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.deployeddriverstable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.deployeddriverstable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.deployeddriverstable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.deployeddriverstable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.deployeddriverstable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.deployeddriverstable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.deployeddriverstable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.deployeddriverstable.setItem(0, 0, item)
        self.deployeddriverstable.horizontalHeader().setStretchLastSection(True)
        self.deployeddriverstable.verticalHeader().setVisible(False)
        self.deployeddriverstable.verticalHeader().setCascadingSectionResizes(False)
        self.deployeddriverstable.verticalHeader().setHighlightSections(False)
        self.horizontalLayout_18.addWidget(self.deployeddriverstable)
        self.deploymentwidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.tab_5)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.tableWidget_8 = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_8.setObjectName("tableWidget_8")
        self.tableWidget_8.setColumnCount(8)
        self.tableWidget_8.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(7, item)
        self.horizontalLayout_19.addWidget(self.tableWidget_8)
        self.deploymentwidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.male = QtWidgets.QCheckBox(self.tab_6)
        self.male.setGeometry(QtCore.QRect(330, 290, 70, 17))
        self.male.setObjectName("male")
        self.emaildriver = QtWidgets.QLineEdit(self.tab_6)
        self.emaildriver.setGeometry(QtCore.QRect(310, 170, 201, 31))
        self.emaildriver.setObjectName("emaildriver")
        self.female = QtWidgets.QCheckBox(self.tab_6)
        self.female.setGeometry(QtCore.QRect(430, 290, 70, 17))
        self.female.setObjectName("female")
        self.label_44 = QtWidgets.QLabel(self.tab_6)
        self.label_44.setGeometry(QtCore.QRect(180, 340, 151, 31))
        self.label_44.setObjectName("label_44")
        self.addressdrive = QtWidgets.QLineEdit(self.tab_6)
        self.addressdrive.setGeometry(QtCore.QRect(310, 210, 201, 31))
        self.addressdrive.setObjectName("addressdrive")
        self.label_45 = QtWidgets.QLabel(self.tab_6)
        self.label_45.setGeometry(QtCore.QRect(180, 90, 131, 21))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.tab_6)
        self.label_46.setGeometry(QtCore.QRect(180, 50, 101, 21))
        self.label_46.setObjectName("label_46")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 470, 131, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.birthdate = QtWidgets.QDateEdit(self.tab_6)
        self.birthdate.setGeometry(QtCore.QRect(310, 251, 181, 31))
        self.birthdate.setObjectName("birthdate")
        self.label_47 = QtWidgets.QLabel(self.tab_6)
        self.label_47.setGeometry(QtCore.QRect(280, 10, 211, 31))
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.tab_6)
        self.label_48.setGeometry(QtCore.QRect(180, 380, 131, 31))
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.tab_6)
        self.label_49.setGeometry(QtCore.QRect(180, 170, 101, 31))
        self.label_49.setObjectName("label_49")
        self.fnamedrive = QtWidgets.QLineEdit(self.tab_6)
        self.fnamedrive.setGeometry(QtCore.QRect(310, 50, 201, 31))
        self.fnamedrive.setObjectName("fnamedrive")
        self.permitclass = QtWidgets.QLineEdit(self.tab_6)
        self.permitclass.setGeometry(QtCore.QRect(300, 380, 201, 31))
        self.permitclass.setObjectName("permitclass")
        self.phonedrive = QtWidgets.QLineEdit(self.tab_6)
        self.phonedrive.setGeometry(QtCore.QRect(310, 130, 201, 31))
        self.phonedrive.setObjectName("phonedrive")
        self.drivephoto = QtWidgets.QLineEdit(self.tab_6)
        self.drivephoto.setGeometry(QtCore.QRect(300, 420, 201, 31))
        self.drivephoto.setObjectName("drivephoto")
        self.label_50 = QtWidgets.QLabel(self.tab_6)
        self.label_50.setGeometry(QtCore.QRect(180, 420, 141, 31))
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.tab_6)
        self.label_51.setGeometry(QtCore.QRect(180, 250, 131, 31))
        self.label_51.setObjectName("label_51")
        self.permitnumber = QtWidgets.QLineEdit(self.tab_6)
        self.permitnumber.setGeometry(QtCore.QRect(300, 340, 201, 31))
        self.permitnumber.setObjectName("permitnumber")
        self.label_52 = QtWidgets.QLabel(self.tab_6)
        self.label_52.setGeometry(QtCore.QRect(180, 130, 121, 21))
        self.label_52.setObjectName("label_52")
        self.lnamedrive = QtWidgets.QLineEdit(self.tab_6)
        self.lnamedrive.setGeometry(QtCore.QRect(310, 90, 201, 31))
        self.lnamedrive.setObjectName("lnamedrive")
        self.label_53 = QtWidgets.QLabel(self.tab_6)
        self.label_53.setGeometry(QtCore.QRect(180, 290, 151, 31))
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.tab_6)
        self.label_54.setGeometry(QtCore.QRect(180, 210, 121, 31))
        self.label_54.setObjectName("label_54")
        self.deploymentwidget.addTab(self.tab_6, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.frame_3 = QtWidgets.QFrame(self.tab_14)
        self.frame_3.setGeometry(QtCore.QRect(240, 120, 382, 134))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_55 = QtWidgets.QLabel(self.frame_3)
        self.label_55.setGeometry(QtCore.QRect(130, 10, 111, 16))
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.frame_3)
        self.label_56.setGeometry(QtCore.QRect(30, 50, 81, 16))
        self.label_56.setObjectName("label_56")
        self.removedriveremove = QtWidgets.QPushButton(self.frame_3)
        self.removedriveremove.setGeometry(QtCore.QRect(100, 90, 75, 31))
        self.removedriveremove.setObjectName("removedriveremove")
        self.removedriveclose = QtWidgets.QPushButton(self.frame_3)
        self.removedriveclose.setGeometry(QtCore.QRect(220, 90, 81, 31))
        self.removedriveclose.setObjectName("removedriveclose")
        self.comboBox_4 = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_4.setGeometry(QtCore.QRect(140, 40, 211, 31))
        self.comboBox_4.setEditable(True)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.deploymentwidget.addTab(self.tab_14, "")
        self.horizontalLayout_4.addWidget(self.deploymentwidget)
        self.mainstackwidget.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget()
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.carswidget = QtWidgets.QTabWidget(self.widget_2)
        self.carswidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.carswidget.setObjectName("carswidget")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.tab_15)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.tableWidget_9 = QtWidgets.QTableWidget(self.tab_15)
        self.tableWidget_9.setObjectName("tableWidget_9")
        self.tableWidget_9.setColumnCount(3)
        self.tableWidget_9.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_20.addWidget(self.tableWidget_9)
        self.carswidget.addTab(self.tab_15, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.tab_7)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame = QtWidgets.QFrame(self.tab_7)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(310, 470, 131, 31))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(200, 130, 81, 31))
        self.label_2.setObjectName("label_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(350, 290, 171, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(350, 130, 171, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(350, 210, 171, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(200, 180, 121, 16))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(200, 290, 121, 21))
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(300, 80, 101, 16))
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(350, 170, 171, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(200, 220, 71, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_5.setGeometry(QtCore.QRect(350, 250, 171, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(200, 250, 81, 31))
        self.label_4.setObjectName("label_4")
        self.deploymentdescription = QtWidgets.QTextEdit(self.frame)
        self.deploymentdescription.setGeometry(QtCore.QRect(350, 340, 191, 101))
        self.deploymentdescription.setObjectName("deploymentdescription")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(200, 360, 131, 16))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_14.addWidget(self.frame)
        self.carswidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.tab_8)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tab_8)
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(4)
        self.tableWidget_6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(3, item)
        self.horizontalLayout_17.addWidget(self.tableWidget_6)
        self.carswidget.addTab(self.tab_8, "")
        self.tab_18 = QtWidgets.QWidget()
        self.tab_18.setObjectName("tab_18")
        self.carswidget.addTab(self.tab_18, "")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.frame_2 = QtWidgets.QFrame(self.tab_17)
        self.frame_2.setGeometry(QtCore.QRect(10, 30, 775, 440))
        self.frame_2.setAutoFillBackground(True)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(580, 100, 181, 31))
        self.lineEdit_7.setAutoFillBackground(False)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(10, 290, 101, 31))
        self.label_9.setObjectName("label_9")
        self.initial_mileage = QtWidgets.QLineEdit(self.frame_2)
        self.initial_mileage.setGeometry(QtCore.QRect(190, 220, 181, 31))
        self.initial_mileage.setAutoFillBackground(False)
        self.initial_mileage.setObjectName("initial_mileage")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(10, 230, 46, 13))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(580, 340, 181, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.manudate = QtWidgets.QDateEdit(self.frame_2)
        self.manudate.setGeometry(QtCore.QRect(190, 140, 181, 31))
        self.manudate.setAutoFillBackground(True)
        self.manudate.setObjectName("manudate")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(10, 60, 141, 31))
        self.label_10.setObjectName("label_10")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_8.setGeometry(QtCore.QRect(580, 260, 181, 31))
        self.lineEdit_8.setAutoFillBackground(False)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.fuel_type = QtWidgets.QComboBox(self.frame_2)
        self.fuel_type.setGeometry(QtCore.QRect(190, 180, 181, 31))
        self.fuel_type.setAutoFillBackground(True)
        self.fuel_type.setObjectName("fuel_type")
        self.fuel_type.addItem("")
        self.fuel_type.addItem("")
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(400, 60, 151, 20))
        self.label_14.setObjectName("label_14")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(10, 180, 121, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(400, 310, 131, 21))
        self.label_12.setObjectName("label_12")
        self.expirydate = QtWidgets.QDateEdit(self.frame_2)
        self.expirydate.setGeometry(QtCore.QRect(580, 180, 181, 31))
        self.expirydate.setObjectName("expirydate")
        self.subscriptiondate = QtWidgets.QDateEdit(self.frame_2)
        self.subscriptiondate.setGeometry(QtCore.QRect(580, 140, 181, 31))
        self.subscriptiondate.setAutoFillBackground(True)
        self.subscriptiondate.setObjectName("subscriptiondate")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(300, 10, 191, 31))
        self.label_13.setObjectName("label_13")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_9.setGeometry(QtCore.QRect(580, 220, 181, 31))
        self.lineEdit_9.setAutoFillBackground(False)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(10, 140, 131, 31))
        self.label_15.setObjectName("label_15")
        self.InsuranceCompany = QtWidgets.QLabel(self.frame_2)
        self.InsuranceCompany.setGeometry(QtCore.QRect(400, 100, 151, 21))
        self.InsuranceCompany.setObjectName("InsuranceCompany")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_10.setGeometry(QtCore.QRect(580, 300, 181, 31))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.addcar = QtWidgets.QPushButton(self.frame_2)
        self.addcar.setGeometry(QtCore.QRect(300, 390, 181, 31))
        self.addcar.setAutoFillBackground(True)
        self.addcar.setObjectName("addcar")
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setGeometry(QtCore.QRect(400, 270, 141, 21))
        self.label_16.setObjectName("label_16")
        self.carcolor = QtWidgets.QLineEdit(self.frame_2)
        self.carcolor.setGeometry(QtCore.QRect(580, 60, 181, 31))
        self.carcolor.setAutoFillBackground(False)
        self.carcolor.setObjectName("carcolor")
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setGeometry(QtCore.QRect(400, 220, 121, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(400, 340, 121, 21))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setGeometry(QtCore.QRect(10, 210, 151, 31))
        self.label_19.setObjectName("label_19")
        self.licensenumber = QtWidgets.QLineEdit(self.frame_2)
        self.licensenumber.setGeometry(QtCore.QRect(190, 60, 181, 31))
        self.licensenumber.setAutoFillBackground(False)
        self.licensenumber.setObjectName("licensenumber")
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        self.label_20.setGeometry(QtCore.QRect(10, 330, 161, 21))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame_2)
        self.label_21.setGeometry(QtCore.QRect(400, 180, 151, 31))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame_2)
        self.label_22.setGeometry(QtCore.QRect(10, 100, 101, 21))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame_2)
        self.label_23.setGeometry(QtCore.QRect(10, 260, 91, 21))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame_2)
        self.label_24.setGeometry(QtCore.QRect(390, 140, 181, 31))
        self.label_24.setObjectName("label_24")
        self.carmake = QtWidgets.QLineEdit(self.frame_2)
        self.carmake.setGeometry(QtCore.QRect(190, 260, 181, 31))
        self.carmake.setAutoFillBackground(False)
        self.carmake.setObjectName("carmake")
        self.cartype = QtWidgets.QLineEdit(self.frame_2)
        self.cartype.setGeometry(QtCore.QRect(190, 300, 181, 31))
        self.cartype.setAutoFillBackground(False)
        self.cartype.setObjectName("cartype")
        self.chasisnumber = QtWidgets.QLineEdit(self.frame_2)
        self.chasisnumber.setGeometry(QtCore.QRect(190, 340, 181, 31))
        self.chasisnumber.setObjectName("chasisnumber")
        self.carmodel = QtWidgets.QLineEdit(self.frame_2)
        self.carmodel.setGeometry(QtCore.QRect(190, 100, 181, 31))
        self.carmodel.setAutoFillBackground(False)
        self.carmodel.setObjectName("carmodel")
        self.carswidget.addTab(self.tab_17, "")
        self.tab_19 = QtWidgets.QWidget()
        self.tab_19.setObjectName("tab_19")
        self.frame_4 = QtWidgets.QFrame(self.tab_19)
        self.frame_4.setGeometry(QtCore.QRect(180, 100, 382, 134))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_57 = QtWidgets.QLabel(self.frame_4)
        self.label_57.setGeometry(QtCore.QRect(130, 10, 111, 16))
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.frame_4)
        self.label_58.setGeometry(QtCore.QRect(10, 40, 141, 31))
        self.label_58.setObjectName("label_58")
        self.removedriveremove_2 = QtWidgets.QPushButton(self.frame_4)
        self.removedriveremove_2.setGeometry(QtCore.QRect(100, 90, 75, 31))
        self.removedriveremove_2.setObjectName("removedriveremove_2")
        self.removedriveclose_2 = QtWidgets.QPushButton(self.frame_4)
        self.removedriveclose_2.setGeometry(QtCore.QRect(220, 90, 81, 31))
        self.removedriveclose_2.setObjectName("removedriveclose_2")
        self.removecarlicence = QtWidgets.QComboBox(self.frame_4)
        self.removecarlicence.setGeometry(QtCore.QRect(180, 41, 151, 31))
        self.removecarlicence.setObjectName("removecarlicence")
        self.removecarlicence.addItem("")
        self.carswidget.addTab(self.tab_19, "")
        self.horizontalLayout_5.addWidget(self.carswidget)
        self.mainstackwidget.addWidget(self.widget_2)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.page_6)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.searchwidget = QtWidgets.QTabWidget(self.page_6)
        self.searchwidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.searchwidget.setObjectName("searchwidget")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_16)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_5 = QtWidgets.QFrame(self.tab_16)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_59 = QtWidgets.QLabel(self.frame_5)
        self.label_59.setObjectName("label_59")
        self.horizontalLayout_23.addWidget(self.label_59)
        self.searchquery = QtWidgets.QLineEdit(self.frame_5)
        self.searchquery.setObjectName("searchquery")
        self.horizontalLayout_23.addWidget(self.searchquery)
        self.searchresults = QtWidgets.QPushButton(self.frame_5)
        self.searchresults.setObjectName("searchresults")
        self.horizontalLayout_23.addWidget(self.searchresults)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.tab_16)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.tableWidget_10 = QtWidgets.QTableWidget(self.frame_6)
        self.tableWidget_10.setObjectName("tableWidget_10")
        self.tableWidget_10.setColumnCount(0)
        self.tableWidget_10.setRowCount(0)
        self.horizontalLayout_22.addWidget(self.tableWidget_10)
        self.verticalLayout.addWidget(self.frame_6)
        self.searchwidget.addTab(self.tab_16, "")
        self.horizontalLayout_21.addWidget(self.searchwidget)
        self.mainstackwidget.addWidget(self.page_6)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.page_4)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.userwidget = QtWidgets.QTabWidget(self.page_4)
        self.userwidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.userwidget.setObjectName("userwidget")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.userwidget.addTab(self.tab_10, "")
        self.horizontalLayout_15.addWidget(self.userwidget)
        self.mainstackwidget.addWidget(self.page_4)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.reporting = QtWidgets.QTabWidget(self.page_3)
        self.reporting.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.reporting.setObjectName("reporting")
        self.carreportstab = QtWidgets.QWidget()
        self.carreportstab.setObjectName("carreportstab")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.carreportstab)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tableWidget = QtWidgets.QTableWidget(self.carreportstab)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout_8.addWidget(self.tableWidget)
        self.reporting.addTab(self.carreportstab, "")
        self.driverreportstab = QtWidgets.QWidget()
        self.driverreportstab.setObjectName("driverreportstab")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.driverreportstab)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.driverreportstab)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.horizontalLayout_9.addWidget(self.tableWidget_2)
        self.reporting.addTab(self.driverreportstab, "")
        self.deploymentreportstab = QtWidgets.QWidget()
        self.deploymentreportstab.setObjectName("deploymentreportstab")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.deploymentreportstab)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.deploymentreportstab)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.horizontalLayout_10.addWidget(self.tableWidget_3)
        self.reporting.addTab(self.deploymentreportstab, "")
        self.servicereportstab = QtWidgets.QWidget()
        self.servicereportstab.setObjectName("servicereportstab")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.servicereportstab)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.servicereportstab)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(0)
        self.tableWidget_4.setRowCount(0)
        self.horizontalLayout_11.addWidget(self.tableWidget_4)
        self.reporting.addTab(self.servicereportstab, "")
        self.repairreportstab = QtWidgets.QWidget()
        self.repairreportstab.setObjectName("repairreportstab")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.repairreportstab)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.repairreportstab)
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(0)
        self.tableWidget_5.setRowCount(0)
        self.horizontalLayout_12.addWidget(self.tableWidget_5)
        self.reporting.addTab(self.repairreportstab, "")
        self.uncertainitiesreportstab = QtWidgets.QWidget()
        self.uncertainitiesreportstab.setObjectName("uncertainitiesreportstab")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.uncertainitiesreportstab)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.reportswidget = QtWidgets.QTableWidget(self.uncertainitiesreportstab)
        self.reportswidget.setObjectName("reportswidget")
        self.reportswidget.setColumnCount(0)
        self.reportswidget.setRowCount(0)
        self.horizontalLayout_13.addWidget(self.reportswidget)
        self.reporting.addTab(self.uncertainitiesreportstab, "")
        self.horizontalLayout_7.addWidget(self.reporting)
        self.mainstackwidget.addWidget(self.page_3)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.page_5)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.uncertainitywidget = QtWidgets.QTabWidget(self.page_5)
        self.uncertainitywidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.uncertainitywidget.setObjectName("uncertainitywidget")
        self.recordeventtab = QtWidgets.QWidget()
        self.recordeventtab.setObjectName("recordeventtab")
        self.driverid = QtWidgets.QLineEdit(self.recordeventtab)
        self.driverid.setGeometry(QtCore.QRect(610, 70, 151, 31))
        self.driverid.setObjectName("driverid")
        self.label_25 = QtWidgets.QLabel(self.recordeventtab)
        self.label_25.setGeometry(QtCore.QRect(300, 20, 271, 21))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.recordeventtab)
        self.label_26.setGeometry(QtCore.QRect(480, 110, 111, 31))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.recordeventtab)
        self.label_27.setGeometry(QtCore.QRect(110, 220, 121, 31))
        self.label_27.setObjectName("label_27")
        self.accidentdate = QtWidgets.QDateEdit(self.recordeventtab)
        self.accidentdate.setGeometry(QtCore.QRect(270, 160, 161, 31))
        self.accidentdate.setObjectName("accidentdate")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.recordeventtab)
        self.lineEdit_11.setGeometry(QtCore.QRect(290, 110, 151, 31))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.addaccident = QtWidgets.QPushButton(self.recordeventtab)
        self.addaccident.setGeometry(QtCore.QRect(220, 440, 161, 31))
        self.addaccident.setObjectName("addaccident")
        self.label_28 = QtWidgets.QLabel(self.recordeventtab)
        self.label_28.setGeometry(QtCore.QRect(110, 160, 161, 31))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.recordeventtab)
        self.label_29.setGeometry(QtCore.QRect(110, 70, 171, 31))
        self.label_29.setObjectName("label_29")
        self.carid = QtWidgets.QLineEdit(self.recordeventtab)
        self.carid.setGeometry(QtCore.QRect(290, 70, 151, 31))
        self.carid.setObjectName("carid")
        self.label_30 = QtWidgets.QLabel(self.recordeventtab)
        self.label_30.setGeometry(QtCore.QRect(480, 80, 121, 21))
        self.label_30.setObjectName("label_30")
        self.accidentdescription = QtWidgets.QTextEdit(self.recordeventtab)
        self.accidentdescription.setGeometry(QtCore.QRect(270, 200, 371, 71))
        self.accidentdescription.setTabChangesFocus(True)
        self.accidentdescription.setObjectName("accidentdescription")
        self.accidenttype = QtWidgets.QComboBox(self.recordeventtab)
        self.accidenttype.setGeometry(QtCore.QRect(610, 110, 141, 31))
        self.accidenttype.setObjectName("accidenttype")
        self.accidenttype.addItem("")
        self.accidenttype.addItem("")
        self.label_31 = QtWidgets.QLabel(self.recordeventtab)
        self.label_31.setGeometry(QtCore.QRect(110, 110, 101, 31))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.recordeventtab)
        self.label_32.setGeometry(QtCore.QRect(140, 360, 71, 31))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.recordeventtab)
        self.label_33.setGeometry(QtCore.QRect(300, 290, 71, 31))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.recordeventtab)
        self.label_34.setGeometry(QtCore.QRect(110, 295, 91, 21))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.recordeventtab)
        self.label_35.setGeometry(QtCore.QRect(480, 300, 121, 16))
        self.label_35.setObjectName("label_35")
        self.textEdit = QtWidgets.QTextEdit(self.recordeventtab)
        self.textEdit.setGeometry(QtCore.QRect(260, 340, 371, 71))
        self.textEdit.setObjectName("textEdit")
        self.comboBox = QtWidgets.QComboBox(self.recordeventtab)
        self.comboBox.setGeometry(QtCore.QRect(208, 291, 81, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(self.recordeventtab)
        self.comboBox_2.setGeometry(QtCore.QRect(380, 291, 91, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.recordeventtab)
        self.comboBox_3.setGeometry(QtCore.QRect(620, 291, 69, 31))
        self.comboBox_3.setObjectName("comboBox_3")
        self.previouseventsbutton = QtWidgets.QPushButton(self.recordeventtab)
        self.previouseventsbutton.setGeometry(QtCore.QRect(410, 440, 141, 31))
        self.previouseventsbutton.setObjectName("previouseventsbutton")
        self.uncertainitywidget.addTab(self.recordeventtab, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.uncertainitywidget.addTab(self.tab_12, "")
        self.horizontalLayout_16.addWidget(self.uncertainitywidget)
        self.mainstackwidget.addWidget(self.page_5)
        self.horizontalLayout.addWidget(self.mainstackwidget)
        FleetX.setCentralWidget(self.centralwidget)
        self.All_Cars = QtWidgets.QAction(FleetX)
        self.All_Cars.setObjectName("All_Cars")
        self.Deploy_Cars = QtWidgets.QAction(FleetX)
        self.Deploy_Cars.setObjectName("Deploy_Cars")
        self.Edit_Car_Details = QtWidgets.QAction(FleetX)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/edit-car.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Edit_Car_Details.setIcon(icon1)
        self.Edit_Car_Details.setObjectName("Edit_Car_Details")
        self.Add_Car = QtWidgets.QAction(FleetX)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/add-car.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Add_Car.setIcon(icon2)
        self.Add_Car.setObjectName("Add_Car")
        self.Remove_Car = QtWidgets.QAction(FleetX)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/remove-car.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Remove_Car.setIcon(icon3)
        self.Remove_Car.setObjectName("Remove_Car")
        self.All_Drivers = QtWidgets.QAction(FleetX)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/driver.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.All_Drivers.setIcon(icon4)
        self.All_Drivers.setObjectName("All_Drivers")
        self.Deploy_Driver = QtWidgets.QAction(FleetX)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/deploy-driver.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Deploy_Driver.setIcon(icon5)
        self.Deploy_Driver.setObjectName("Deploy_Driver")
        self.Edit_Driver = QtWidgets.QAction(FleetX)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/edit-driver.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Edit_Driver.setIcon(icon6)
        self.Edit_Driver.setObjectName("Edit_Driver")
        self.Add_Driver = QtWidgets.QAction(FleetX)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/add-driver.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Add_Driver.setIcon(icon7)
        self.Add_Driver.setObjectName("Add_Driver")
        self.Remove_Driver = QtWidgets.QAction(FleetX)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/remove-driver.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Remove_Driver.setIcon(icon8)
        self.Remove_Driver.setObjectName("Remove_Driver")
        self.Add_Service_Details = QtWidgets.QAction(FleetX)
        self.Add_Service_Details.setObjectName("Add_Service_Details")
        self.Add_Repair_Details = QtWidgets.QAction(FleetX)
        self.Add_Repair_Details.setObjectName("Add_Repair_Details")
        self.Repairs = QtWidgets.QAction(FleetX)
        self.Repairs.setObjectName("Repairs")
        self.actionService_details = QtWidgets.QAction(FleetX)
        self.actionService_details.setObjectName("actionService_details")
        self.Add_New_Case = QtWidgets.QAction(FleetX)
        self.Add_New_Case.setObjectName("Add_New_Case")
        self.actionView_Previous_Cases = QtWidgets.QAction(FleetX)
        self.actionView_Previous_Cases.setObjectName("actionView_Previous_Cases")
        self.Cars_Reports = QtWidgets.QAction(FleetX)
        self.Cars_Reports.setObjectName("Cars_Reports")
        self.Driver_Reports = QtWidgets.QAction(FleetX)
        self.Driver_Reports.setObjectName("Driver_Reports")
        self.Deployment_Reports = QtWidgets.QAction(FleetX)
        self.Deployment_Reports.setObjectName("Deployment_Reports")
        self.Fuelage_Reports = QtWidgets.QAction(FleetX)
        self.Fuelage_Reports.setObjectName("Fuelage_Reports")
        self.Uncertainity_Reports = QtWidgets.QAction(FleetX)
        self.Uncertainity_Reports.setObjectName("Uncertainity_Reports")
        self.Mileage_Reports = QtWidgets.QAction(FleetX)
        self.Mileage_Reports.setObjectName("Mileage_Reports")
        self.About_User = QtWidgets.QAction(FleetX)
        self.About_User.setObjectName("About_User")
        self.actionEdit_Details = QtWidgets.QAction(FleetX)
        self.actionEdit_Details.setObjectName("actionEdit_Details")
        self.Logout = QtWidgets.QAction(FleetX)
        self.Logout.setObjectName("Logout")
        self.actionExit = QtWidgets.QAction(FleetX)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(FleetX)
        self.menutab.setCurrentIndex(0)
        self.mainstackwidget.setCurrentIndex(2)
        self.servicetab.setCurrentIndex(0)
        self.deploymentwidget.setCurrentIndex(0)
        self.carswidget.setCurrentIndex(0)
        self.searchwidget.setCurrentIndex(0)
        self.userwidget.setCurrentIndex(0)
        self.reporting.setCurrentIndex(0)
        self.uncertainitywidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FleetX)
        FleetX.setTabOrder(self.reportbutton, self.userbutton)
        FleetX.setTabOrder(self.userbutton, self.logoutbutton)
        FleetX.setTabOrder(self.logoutbutton, self.maintenamcebutton)
        FleetX.setTabOrder(self.maintenamcebutton, self.searchbutton)
        FleetX.setTabOrder(self.searchbutton, self.servicetab)
        FleetX.setTabOrder(self.servicetab, self.deploymentwidget)
        FleetX.setTabOrder(self.deploymentwidget, self.fnamedrive)
        FleetX.setTabOrder(self.fnamedrive, self.lnamedrive)
        FleetX.setTabOrder(self.lnamedrive, self.phonedrive)
        FleetX.setTabOrder(self.phonedrive, self.emaildriver)
        FleetX.setTabOrder(self.emaildriver, self.addressdrive)
        FleetX.setTabOrder(self.addressdrive, self.birthdate)
        FleetX.setTabOrder(self.birthdate, self.male)
        FleetX.setTabOrder(self.male, self.female)
        FleetX.setTabOrder(self.female, self.permitnumber)
        FleetX.setTabOrder(self.permitnumber, self.permitclass)
        FleetX.setTabOrder(self.permitclass, self.drivephoto)
        FleetX.setTabOrder(self.drivephoto, self.pushButton_2)
        FleetX.setTabOrder(self.pushButton_2, self.lineEdit_6)
        FleetX.setTabOrder(self.lineEdit_6, self.manudate)
        FleetX.setTabOrder(self.manudate, self.lineEdit_8)
        FleetX.setTabOrder(self.lineEdit_8, self.fuel_type)
        FleetX.setTabOrder(self.fuel_type, self.expirydate)
        FleetX.setTabOrder(self.expirydate, self.driversbutton)
        FleetX.setTabOrder(self.driversbutton, self.carsbutton)
        FleetX.setTabOrder(self.carsbutton, self.subscriptiondate)
        FleetX.setTabOrder(self.subscriptiondate, self.lineEdit_9)
        FleetX.setTabOrder(self.lineEdit_9, self.lineEdit_10)
        FleetX.setTabOrder(self.lineEdit_10, self.addcar)
        FleetX.setTabOrder(self.addcar, self.carcolor)
        FleetX.setTabOrder(self.carcolor, self.licensenumber)
        FleetX.setTabOrder(self.licensenumber, self.carmake)
        FleetX.setTabOrder(self.carmake, self.cartype)
        FleetX.setTabOrder(self.cartype, self.chasisnumber)
        FleetX.setTabOrder(self.chasisnumber, self.carmodel)
        FleetX.setTabOrder(self.carmodel, self.userwidget)
        FleetX.setTabOrder(self.userwidget, self.reporting)
        FleetX.setTabOrder(self.reporting, self.tableWidget)
        FleetX.setTabOrder(self.tableWidget, self.tableWidget_2)
        FleetX.setTabOrder(self.tableWidget_2, self.tableWidget_3)
        FleetX.setTabOrder(self.tableWidget_3, self.tableWidget_4)
        FleetX.setTabOrder(self.tableWidget_4, self.tableWidget_5)
        FleetX.setTabOrder(self.tableWidget_5, self.reportswidget)
        FleetX.setTabOrder(self.reportswidget, self.uncertainitywidget)
        FleetX.setTabOrder(self.uncertainitywidget, self.carid)
        FleetX.setTabOrder(self.carid, self.driverid)
        FleetX.setTabOrder(self.driverid, self.lineEdit_11)
        FleetX.setTabOrder(self.lineEdit_11, self.accidenttype)
        FleetX.setTabOrder(self.accidenttype, self.accidentdate)
        FleetX.setTabOrder(self.accidentdate, self.accidentdescription)
        FleetX.setTabOrder(self.accidentdescription, self.comboBox)
        FleetX.setTabOrder(self.comboBox, self.comboBox_2)
        FleetX.setTabOrder(self.comboBox_2, self.comboBox_3)
        FleetX.setTabOrder(self.comboBox_3, self.textEdit)
        FleetX.setTabOrder(self.textEdit, self.addaccident)
        FleetX.setTabOrder(self.addaccident, self.previouseventsbutton)
        FleetX.setTabOrder(self.previouseventsbutton, self.menutab)
        FleetX.setTabOrder(self.menutab, self.partsservice)
        FleetX.setTabOrder(self.partsservice, self.submitservice)
        FleetX.setTabOrder(self.submitservice, self.drivernumserv)
        FleetX.setTabOrder(self.drivernumserv, self.numcarserv)
        FleetX.setTabOrder(self.numcarserv, self.dateservice)
        FleetX.setTabOrder(self.dateservice, self.servicedescription)
        FleetX.setTabOrder(self.servicedescription, self.serviceinvoice)
        FleetX.setTabOrder(self.serviceinvoice, self.servicebox)
        FleetX.setTabOrder(self.servicebox, self.tableWidget_7)
        FleetX.setTabOrder(self.tableWidget_7, self.deployeddriverstable)
        FleetX.setTabOrder(self.deployeddriverstable, self.tableWidget_8)
        FleetX.setTabOrder(self.tableWidget_8, self.lineEdit_2)
        FleetX.setTabOrder(self.lineEdit_2, self.lineEdit)
        FleetX.setTabOrder(self.lineEdit, self.lineEdit_5)
        FleetX.setTabOrder(self.lineEdit_5, self.pushButton)
        FleetX.setTabOrder(self.pushButton, self.initial_mileage)
        FleetX.setTabOrder(self.initial_mileage, self.uncertainitybutton)
        FleetX.setTabOrder(self.uncertainitybutton, self.carswidget)
        FleetX.setTabOrder(self.carswidget, self.tableWidget_6)
        FleetX.setTabOrder(self.tableWidget_6, self.lineEdit_3)
        FleetX.setTabOrder(self.lineEdit_3, self.lineEdit_7)
        FleetX.setTabOrder(self.lineEdit_7, self.deploymentdescription)
        FleetX.setTabOrder(self.deploymentdescription, self.lineEdit_4)

    def retranslateUi(self, FleetX):
        _translate = QtCore.QCoreApplication.translate
        FleetX.setWindowTitle(_translate("FleetX", "FleetX"))
        self.carsbutton.setText(_translate("FleetX", "Cars"))
        self.driversbutton.setText(_translate("FleetX", "Drivers"))
        self.uncertainitybutton.setText(_translate("FleetX", "Uncertainities"))
        self.reportbutton.setText(_translate("FleetX", "Reports"))
        self.userbutton.setText(_translate("FleetX", "User Details"))
        self.logoutbutton.setText(_translate("FleetX", "Logout"))
        self.maintenamcebutton.setText(_translate("FleetX", "Maintenance"))
        self.searchbutton.setText(_translate("FleetX", "Search"))
        self.label_36.setText(_translate("FleetX", "Service Description"))
        self.label_37.setText(_translate("FleetX", "Parts affectes"))
        self.label_38.setText(_translate("FleetX", "Date of Service"))
        self.label_39.setText(_translate("FleetX", "Enter repair or service details"))
        self.submitservice.setText(_translate("FleetX", "Submit Details"))
        self.label_40.setText(_translate("FleetX", "Invoice Image"))
        self.label_41.setText(_translate("FleetX", "Service Type"))
        self.label_42.setText(_translate("FleetX", "Car licence plate number"))
        self.label_43.setText(_translate("FleetX", "Driver Number"))
        self.servicebox.setItemText(0, _translate("FleetX", "Service"))
        self.servicebox.setItemText(1, _translate("FleetX", "Repair"))
        self.servicetab.setTabText(self.servicetab.indexOf(self.tab), _translate("FleetX", "Service Details"))
        self.servicetab.setTabText(self.servicetab.indexOf(self.tab_2), _translate("FleetX", "Repairs Car"))
        item = self.tableWidget_7.horizontalHeaderItem(0)
        item.setText(_translate("FleetX", "License Number"))
        item = self.tableWidget_7.horizontalHeaderItem(1)
        item.setText(_translate("FleetX", "Driver ID"))
        item = self.tableWidget_7.horizontalHeaderItem(2)
        item.setText(_translate("FleetX", "Date of Activity"))
        item = self.tableWidget_7.horizontalHeaderItem(3)
        item.setText(_translate("FleetX", "Parts Affected"))
        self.servicetab.setTabText(self.servicetab.indexOf(self.tab_11), _translate("FleetX", "Previous Service"))
        self.servicetab.setTabText(self.servicetab.indexOf(self.tab_13), _translate("FleetX", "Previous Repairs"))
        item = self.deployeddriverstable.verticalHeaderItem(0)
        item.setText(_translate("FleetX", "1"))
        item = self.deployeddriverstable.verticalHeaderItem(1)
        item.setText(_translate("FleetX", "New Row"))
        item = self.deployeddriverstable.horizontalHeaderItem(0)
        item.setText(_translate("FleetX", "First Name"))
        item = self.deployeddriverstable.horizontalHeaderItem(1)
        item.setText(_translate("FleetX", "Second Name"))
        item = self.deployeddriverstable.horizontalHeaderItem(2)
        item.setText(_translate("FleetX", "Driver ID"))
        item = self.deployeddriverstable.horizontalHeaderItem(3)
        item.setText(_translate("FleetX", "Car License Number"))
        item = self.deployeddriverstable.horizontalHeaderItem(4)
        item.setText(_translate("FleetX", "Permit Number"))
        item = self.deployeddriverstable.horizontalHeaderItem(5)
        item.setText(_translate("FleetX", "Fuel Card Number"))
        item = self.deployeddriverstable.horizontalHeaderItem(6)
        item.setText(_translate("FleetX", "Origin"))
        item = self.deployeddriverstable.horizontalHeaderItem(7)
        item.setText(_translate("FleetX", "Deployment Time"))
        __sortingEnabled = self.deployeddriverstable.isSortingEnabled()
        self.deployeddriverstable.setSortingEnabled(False)
        self.deployeddriverstable.setSortingEnabled(__sortingEnabled)
        self.deploymentwidget.setTabText(self.deploymentwidget.indexOf(self.tab_4), _translate("FleetX", "Deployed Drivers"))
        item = self.tableWidget_8.horizontalHeaderItem(0)
        item.setText(_translate("FleetX", "First Name"))
        item = self.tableWidget_8.horizontalHeaderItem(1)
        item.setText(_translate("FleetX", "Second Name"))
        item = self.tableWidget_8.horizontalHeaderItem(2)
        item.setText(_translate("FleetX", "Date of Birth"))
        item = self.tableWidget_8.horizontalHeaderItem(3)
        item.setText(_translate("FleetX", "Genda"))
        item = self.tableWidget_8.horizontalHeaderItem(4)
        item.setText(_translate("FleetX", "Permit Number"))
        item = self.tableWidget_8.horizontalHeaderItem(5)
        item.setText(_translate("FleetX", "Date Added"))
        item = self.tableWidget_8.horizontalHeaderItem(6)
        item.setText(_translate("FleetX", "Experience"))
        item = self.tableWidget_8.horizontalHeaderItem(7)
        item.setText(_translate("FleetX", "Status"))
        self.deploymentwidget.setTabText(self.deploymentwidget.indexOf(self.tab_5), _translate("FleetX", "All Drivers"))
        self.male.setText(_translate("FleetX", "Male"))
        self.female.setText(_translate("FleetX", "Female"))
        self.label_44.setText(_translate("FleetX", "Permit Number"))
        self.label_45.setText(_translate("FleetX", "Last Name"))
        self.label_46.setText(_translate("FleetX", "First Name"))
        self.pushButton_2.setText(_translate("FleetX", "Add Driver"))
        self.label_47.setText(_translate("FleetX", "Add New Driver\'s Details"))
        self.label_48.setText(_translate("FleetX", "Permit Class"))
        self.label_49.setText(_translate("FleetX", "Email Address"))
        self.label_50.setText(_translate("FleetX", "Photo"))
        self.label_51.setText(_translate("FleetX", "Date of Birth"))
        self.label_52.setText(_translate("FleetX", "Phone Number"))
        self.label_53.setText(_translate("FleetX", "Gender"))
        self.label_54.setText(_translate("FleetX", "Address"))
        self.deploymentwidget.setTabText(self.deploymentwidget.indexOf(self.tab_6), _translate("FleetX", "Add Driver"))
        self.label_55.setText(_translate("FleetX", "Remove Driver"))
        self.label_56.setText(_translate("FleetX", "Drive ID"))
        self.removedriveremove.setText(_translate("FleetX", "Remove"))
        self.removedriveclose.setText(_translate("FleetX", "Close"))
        self.comboBox_4.setItemText(0, _translate("FleetX", "Choose Drive ID"))
        self.deploymentwidget.setTabText(self.deploymentwidget.indexOf(self.tab_14), _translate("FleetX", "Remove Driver"))
        item = self.tableWidget_9.horizontalHeaderItem(0)
        item.setText(_translate("FleetX", "License Number"))
        item = self.tableWidget_9.horizontalHeaderItem(1)
        item.setText(_translate("FleetX", "Type"))
        item = self.tableWidget_9.horizontalHeaderItem(2)
        item.setText(_translate("FleetX", "Status"))
        self.carswidget.setTabText(self.carswidget.indexOf(self.tab_15), _translate("FleetX", "All Cars"))
        self.pushButton.setText(_translate("FleetX", "Deploy Car"))
        self.label_2.setText(_translate("FleetX", "Car Number"))
        self.label_3.setText(_translate("FleetX", "Drive Number"))
        self.label_5.setText(_translate("FleetX", "Fuel Card Number"))
        self.label.setText(_translate("FleetX", "DEPLOY CAR"))
        self.label_6.setText(_translate("FleetX", "Origin"))
        self.label_4.setText(_translate("FleetX", "Destination"))
        self.label_7.setText(_translate("FleetX", "Deployment Description"))
        self.carswidget.setTabText(self.carswidget.indexOf(self.tab_7), _translate("FleetX", "Deploy Car"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("FleetX", "Licence Number"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("FleetX", "Driver ID"))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("FleetX", "Origin "))
        item = self.tableWidget_6.horizontalHeaderItem(3)
        item.setText(_translate("FleetX", "Time Deploy"))
        self.carswidget.setTabText(self.carswidget.indexOf(self.tab_8), _translate("FleetX", "Deployed Cars"))
        self.carswidget.setTabText(self.carswidget.indexOf(self.tab_18), _translate("FleetX", "Edit Car"))
        self.label_9.setText(_translate("FleetX", "Type"))
        self.label_10.setText(_translate("FleetX", "License plate number"))
        self.fuel_type.setItemText(0, _translate("FleetX", "Petrol"))
        self.fuel_type.setItemText(1, _translate("FleetX", "Deisel"))
        self.label_14.setText(_translate("FleetX", "Color"))
        self.label_11.setText(_translate("FleetX", "Fuel Type"))
        self.label_12.setText(_translate("FleetX", "Left Side Photo"))
        self.label_13.setText(_translate("FleetX", "ADD CAR DETAILS"))
        self.label_15.setText(_translate("FleetX", "Manufacture Date"))
        self.InsuranceCompany.setText(_translate("FleetX", "Insurance Company"))
        self.addcar.setText(_translate("FleetX", "Add Car"))
        self.label_16.setText(_translate("FleetX", "Right Side Photo"))
        self.label_17.setText(_translate("FleetX", "Front Photo"))
        self.label_18.setText(_translate("FleetX", "Behind Photo"))
        self.label_19.setText(_translate("FleetX", "Mileage"))
        self.label_20.setText(_translate("FleetX", "Chasis Number"))
        self.label_21.setText(_translate("FleetX", "3rd party expiry date"))
        self.label_22.setText(_translate("FleetX", "Car Model"))
        self.label_23.setText(_translate("FleetX", "Make"))
        self.label_24.setText(_translate("FleetX", "3rd Party Subscpriton date"))
        self.carswidget.setTabText(self.carswidget.indexOf(self.tab_17), _translate("FleetX", "Add Car"))
        self.label_57.setText(_translate("FleetX", "Remove Car"))
        self.label_58.setText(_translate("FleetX", "Car Licence Number"))
        self.removedriveremove_2.setText(_translate("FleetX", "Remove"))
        self.removedriveclose_2.setText(_translate("FleetX", "Close"))
        self.removecarlicence.setItemText(0, _translate("FleetX", "Enter License Number"))
        self.carswidget.setTabText(self.carswidget.indexOf(self.tab_19), _translate("FleetX", "Remove Car"))
        self.label_59.setText(_translate("FleetX", "Text"))
        self.searchresults.setText(_translate("FleetX", "Search"))
        self.searchwidget.setTabText(self.searchwidget.indexOf(self.tab_16), _translate("FleetX", "Search Everything"))
        self.userwidget.setTabText(self.userwidget.indexOf(self.tab_10), _translate("FleetX", "User Details"))
        self.reporting.setTabText(self.reporting.indexOf(self.carreportstab), _translate("FleetX", "Car Reports"))
        self.reporting.setTabText(self.reporting.indexOf(self.driverreportstab), _translate("FleetX", "Driver Reports"))
        self.reporting.setTabText(self.reporting.indexOf(self.deploymentreportstab), _translate("FleetX", "Deployment Reports"))
        self.reporting.setTabText(self.reporting.indexOf(self.servicereportstab), _translate("FleetX", "Service Reports"))
        self.reporting.setTabText(self.reporting.indexOf(self.repairreportstab), _translate("FleetX", "Repair Reports"))
        self.reporting.setTabText(self.reporting.indexOf(self.uncertainitiesreportstab), _translate("FleetX", "Uncertainity Reports"))
        self.label_25.setText(_translate("FleetX", "Add accident event"))
        self.label_26.setText(_translate("FleetX", "Type"))
        self.label_27.setText(_translate("FleetX", "Brief description"))
        self.addaccident.setText(_translate("FleetX", "Add Event"))
        self.label_28.setText(_translate("FleetX", "Event Time"))
        self.label_29.setText(_translate("FleetX", "Car Licence Plate Number"))
        self.label_30.setText(_translate("FleetX", "Drive ID"))
        self.accidenttype.setItemText(0, _translate("FleetX", "Fatal"))
        self.accidenttype.setItemText(1, _translate("FleetX", "Non Fatal"))
        self.label_31.setText(_translate("FleetX", "Location"))
        self.label_32.setText(_translate("FleetX", "Resolution"))
        self.label_33.setText(_translate("FleetX", "car status"))
        self.label_34.setText(_translate("FleetX", "Driver Status"))
        self.label_35.setText(_translate("FleetX", "Passenger Status"))
        self.previouseventsbutton.setText(_translate("FleetX", "View Preious Events"))
        self.uncertainitywidget.setTabText(self.uncertainitywidget.indexOf(self.recordeventtab), _translate("FleetX", "Record Event"))
        self.uncertainitywidget.setTabText(self.uncertainitywidget.indexOf(self.tab_12), _translate("FleetX", "Previous Events"))
        self.All_Cars.setText(_translate("FleetX", "All Cars"))
        self.Deploy_Cars.setText(_translate("FleetX", "Deploy Cars"))
        self.Edit_Car_Details.setText(_translate("FleetX", "Edit Car Details"))
        self.Add_Car.setText(_translate("FleetX", "Add Car"))
        self.Remove_Car.setText(_translate("FleetX", "Remove Car"))
        self.All_Drivers.setText(_translate("FleetX", "All Drivers"))
        self.Deploy_Driver.setText(_translate("FleetX", "Deploy Driver"))
        self.Edit_Driver.setText(_translate("FleetX", "Edit Driver"))
        self.Add_Driver.setText(_translate("FleetX", "Add Driver"))
        self.Remove_Driver.setText(_translate("FleetX", "Remove Driver"))
        self.Add_Service_Details.setText(_translate("FleetX", "Add Service Details"))
        self.Add_Repair_Details.setText(_translate("FleetX", "Add Repair Details"))
        self.Repairs.setText(_translate("FleetX", "Repairs details"))
        self.actionService_details.setText(_translate("FleetX", "Service details"))
        self.Add_New_Case.setText(_translate("FleetX", "Add New Case"))
        self.actionView_Previous_Cases.setText(_translate("FleetX", "View Previous Cases"))
        self.Cars_Reports.setText(_translate("FleetX", "Cars Reports"))
        self.Driver_Reports.setText(_translate("FleetX", "Driver Reports"))
        self.Deployment_Reports.setText(_translate("FleetX", "Deployment Reports"))
        self.Fuelage_Reports.setText(_translate("FleetX", "Fuelage Reports"))
        self.Uncertainity_Reports.setText(_translate("FleetX", "Uncertainity Reports"))
        self.Mileage_Reports.setText(_translate("FleetX", "Mileage Reports"))
        self.About_User.setText(_translate("FleetX", "About User"))
        self.actionEdit_Details.setText(_translate("FleetX", "Edit Details"))
        self.Logout.setText(_translate("FleetX", "Logout"))
        self.actionExit.setText(_translate("FleetX", "Exit"))

import icons_rc
